// Entry data for the Flying Atlas prototype.
// tier: 1 world, 2 country, 3 region, 4 detail. hidden: only revealed on hover.
// domain: site | heritage | nature | aviation
window.ATLAS_ENTRIES = [
  // ---------- HOME ----------
  {id:"oslo-home", t:1, dom:"aviation", lat:59.91, lon:10.75, name:"Paragliding Atlas, Oslo", place:"Oslo, Norway",
   hook:"Where every episode of the show starts.",
   body:["This is home base. The stories on this globe come from the pilots who sat down with me on the show, and from the places I fly myself.",
         "Pins glow in orange. The faint green dots are things you only find by hovering. Zoom in and more appears."],
   rel:["kerio-valley","bir-billing","mieussy"]},

  // ---------- KENYA ----------
  {id:"kerio-valley", t:1, dom:"site", lat:0.61, lon:35.54, name:"Kerio Valley", place:"Elgeyo escarpment, Kenya", alt:"Takeoff 2,400 m, landing 1,100 m",
   hook:"A 1,300 m escarpment that works from breakfast until sunset.",
   body:["The Elgeyo escarpment faces east over the Kerio Valley. Morning sun warms the wall, the valley breeze arrives mid morning, and the ridge then works for hours. Flights run north and south along the lip for tens of kilometres with the valley floor 1,000 m below.",
         "My Kenya tours fly here in January and February, the driest and most reliable window. Rating IPPI 2 or equivalent."],
   fly:{window:"E to SE (060 to 140)",max:"28 km/h at takeoff",season:"Jan to Mar, Oct to Nov",sample:{wind:14,dir:95,gust:21,base:"3,100 m",verdict:"go",why:"Wind is inside the window and gusts sit under the margin."}},
   rel:["iten","elgeyo-run","great-rift-valley","ruppells-vulture"]},
  {id:"elgeyo-run", t:3, dom:"site", lat:1.05, lon:35.6, name:"The escarpment run", place:"Elgeyo escarpment, Kenya",
   hook:"The classic line: north along the lip, land back at Kessup.",
   body:["The standard cross country here is simple to describe and hard to finish. Launch at Kessup, climb in the first thermals off the wall, then run north along the escarpment toward Kapcherop and turn for home before the afternoon overdevelops.",
         "The line drawn on the globe is illustrative, taken from how pilots describe the route, not from a live tracklog. Switch on the Trails layer to see it."],
   rel:["kerio-valley"]},
  {id:"iten", t:3, dom:"heritage", lat:0.67, lon:35.51, name:"Iten, Home of Champions", place:"Elgeyo Marakwet, Kenya",
   hook:"A town at 2,400 m that produces more marathon winners than most countries.",
   body:["The takeoff sits a short drive from Iten, the high altitude training town where a large share of the world's best distance runners live and train. The same thin air that makes runners strong makes takeoff runs longer, so wait for the cycle before you commit.",
         "Walk the town in the early morning and you share the road with training groups moving at a pace you cannot follow."],
   rel:["kerio-valley"]},
  {id:"great-rift-valley", t:1, dom:"nature", lat:-0.5, lon:36.1, name:"Great Rift Valley lakes", place:"Kenya, UNESCO World Heritage",
   hook:"Where the continent is slowly tearing itself in two.",
   body:["The Kenya Lake System, Bogoria, Nakuru and Elementaita, is a UNESCO site for its flamingo flocks and the sheer number of bird species that stop here. The valley itself is a crack in the African plate that widens by a few millimetres a year.",
         "For pilots the rift is a thermal factory. The valley floor heats fast, the escarpment walls on either side give you a ridge, and the lakes mark where the air cools and the lift dies."],
   rel:["kerio-valley","hells-gate","lake-turkana"]},
  {id:"lake-turkana", t:2, dom:"heritage", lat:4.1, lon:35.9, name:"Cradle of humankind", place:"Lake Turkana, Kenya, UNESCO World Heritage",
   hook:"A 1.6 million year old boy found on the lake shore.",
   body:["In 1984 a nearly complete skeleton of a Homo erectus youth, now called Turkana Boy, was dug out of the Nariokotome river bed on the west shore of Lake Turkana. The Koobi Fora fossil beds on the east side have given up thousands more early human finds.",
         "The lake is the largest desert lake in the world, jade green from algae, and the wind here is relentless. It is not a flying site. It is the reason the flying sites exist, because this is where the first people looked up."],
   rel:["great-rift-valley","kerio-valley"]},
  {id:"mount-kenya", t:2, dom:"nature", lat:-0.15, lon:37.31, name:"Mount Kenya", place:"Kenya, UNESCO World Heritage",
   hook:"Equatorial glaciers on a 5,199 m volcanic stump.",
   body:["Africa's second highest peak is the eroded core of an ancient volcano. It still carries small glaciers on the equator, though they are shrinking fast. The mountain makes its own weather and its cloud cap is a daily forecast for anyone flying within sight of it.",
         "The Kikuyu people call it Kirinyaga, the place of brightness, and hold it as the home of God."],
   rel:["great-rift-valley"]},
  {id:"hells-gate", t:3, dom:"nature", lat:-0.9, lon:36.32, name:"Hell's Gate gorge", place:"Naivasha, Kenya",
   hook:"Steam vents, red cliffs and the park you can cycle through.",
   body:["A narrow gorge cut through volcanic rock south of Lake Naivasha, with geothermal steam rising from the ground. It is one of the few national parks in Kenya where you can walk and cycle among the wildlife, because there are no lions.",
         "The cliffs are a nesting place for vultures and eagles, which is why the thermals here are already occupied when you arrive."],
   rel:["ruppells-vulture","great-rift-valley"]},
  {id:"ruppells-vulture", t:3, dom:"nature", hidden:true, lat:-0.84, lon:36.36, name:"Ruppell's vulture", place:"Hell's Gate cliffs, Kenya",
   hook:"The highest flying bird on record, 11,300 m.",
   body:["In 1973 a Ruppell's vulture was struck by an airliner at 11,300 m over Ivory Coast. The species soars on thermals for hours without a wingbeat, which is the entire idea behind our sport. Watch one and you learn where the core is.",
         "They nest on the cliffs of Hell's Gate and along the Rift escarpments. If you share a thermal with one, follow it. It has more hours than you."],
   rel:["hells-gate","kerio-valley","himalayan-griffon"]},
  {id:"maasai-mara", t:3, dom:"nature", hidden:true, lat:-1.5, lon:35.14, name:"The great migration", place:"Maasai Mara, Kenya",
   hook:"Over a million wildebeest cross the Mara river every year.",
   body:["Between July and October the herds move north from the Serengeti into the Mara, crossing rivers full of crocodiles. From the air it reads as a dark tide moving across the grass.",
         "Balloon flights over the Mara at dawn are one of the few aerial experiences here. Paragliding is not allowed inside the reserve."],
   rel:["great-rift-valley"]},
  {id:"lamu", t:3, dom:"heritage", lat:-2.27, lon:40.9, name:"Lamu Old Town", place:"Kenya coast, UNESCO World Heritage",
   hook:"The oldest living Swahili town, with no cars and a lot of donkeys.",
   body:["Lamu has been a trading port since the 1300s, built in coral stone and mangrove timber. The lanes are too narrow for cars so goods move by donkey and dhow. It is the best preserved Swahili settlement in East Africa.",
         "The coast is a good decompression after a week on the escarpment, and the monsoon wind patterns here, the kaskazi and the kusi, decide the sailing season the same way they once decided the trading season."],
   rel:["fort-jesus","gedi"]},
  {id:"fort-jesus", t:3, dom:"heritage", lat:-4.06, lon:39.68, name:"Fort Jesus", place:"Mombasa, Kenya, UNESCO World Heritage",
   hook:"A Portuguese fort shaped like a man, built in 1593.",
   body:["Seen from above the fort has the outline of a human figure, head toward the sea. It changed hands nine times between Portuguese, Omani Arabs and the British, and is the best example of 16th century Portuguese military architecture outside Europe."],
   rel:["lamu"]},
  {id:"gedi", t:4, dom:"heritage", lat:-3.31, lon:40.02, name:"Gedi ruins", place:"Near Malindi, Kenya",
   hook:"A Swahili city abandoned in the 1600s and swallowed by forest.",
   body:["Gedi was a wealthy coastal city with a palace, a great mosque and houses with indoor plumbing. Then everyone left, and nobody is certain why. The forest took it back and it stayed hidden until the 1920s.",
         "Chinese porcelain and Venetian glass found in the ruins show how far the Indian Ocean trade reached."],
   rel:["lamu","fort-jesus"]},
  {id:"thimlich", t:4, dom:"heritage", hidden:true, lat:-0.95, lon:34.3, name:"Thimlich Ohinga", place:"Migori, Kenya, UNESCO World Heritage",
   hook:"Dry stone walls built without mortar, standing for 500 years.",
   body:["A fortified settlement near Lake Victoria built from loose stones stacked without any binding, in walls up to 4.5 m high. It is the largest and best preserved of hundreds of similar enclosures in the region."],
   rel:["lake-turkana"]},
  {id:"beryl-markham", t:3, dom:"aviation", lat:-1.32, lon:36.82, name:"Beryl Markham", place:"Nairobi, Kenya",
   hook:"The first person to fly the Atlantic solo from east to west, 1936.",
   body:["Markham grew up in Kenya, worked as a bush pilot spotting elephant herds for safaris, and in September 1936 flew a Vega Gull alone from England to Nova Scotia, into the prevailing wind. She crash landed in a bog with the fuel line iced up, and walked away.",
         "Her book West with the Night is one of the best things ever written about flying. The Trails layer shows her crossing."],
   rel:["lindbergh","oslo-home"]},

  // ---------- INDIA ----------
  {id:"bir-billing", t:1, dom:"site", lat:32.04, lon:76.73, name:"Bir Billing", place:"Himachal Pradesh, India", alt:"Takeoff Billing 2,400 m, landing Bir 1,400 m",
   hook:"The big mountain site of Asia. Launch at 2,400 m, land in a Tibetan village.",
   body:["Billing takeoff is a grass meadow at 2,400 m on the Dhauladhar front range, with the Kangra plains 1,000 m below and the Himalaya at your back. Thermals start on the spur below launch and the classic flying is along the range, west toward Dharamshala.",
         "My India tour, Big Mountain Flying, runs here in October and November with one guide to three pilots. Rating IPPI 2 or equivalent. The World Cup came here in 2015 and the site has been on every pilot's list since."],
   fly:{window:"SE to SW (130 to 230)",max:"25 km/h at takeoff",season:"Oct to Nov, Mar to May",sample:{wind:11,dir:180,gust:19,base:"3,800 m",verdict:"go",why:"Straight up the face and the base is high. A classic Billing morning."}},
   rel:["bir-dharamshala-run","dhauladhar","sherabling","himalayan-griffon"]},
  {id:"bir-dharamshala-run", t:3, dom:"site", lat:32.14, lon:76.5, name:"Billing to Dharamshala", place:"Dhauladhar range, India",
   hook:"The 35 km out along the range that every visiting pilot wants.",
   body:["Climb above launch, push west over the spur at Bara Bhangal gap, and follow the front range. The Dhauladhar wall on your right runs to over 4,000 m and the cloudbase on a good day sits above it. Turn at Dharamshala and come home with the afternoon.",
         "Drawn here as an illustrative line from how pilots describe it, not a live tracklog. Toggle the Trails layer."],
   rel:["bir-billing","dharamshala"]},
  {id:"dhauladhar", t:2, dom:"nature", lat:32.3, lon:76.5, name:"The Dhauladhar", place:"Himachal Pradesh, India",
   hook:"A 4,000 m wall that rises out of the plains in a single step.",
   body:["The White Range is the outer rampart of the Himalaya. It climbs from 500 m on the Kangra plain to over 4,500 m within 20 km, one of the steepest rises on earth. That step is what makes Billing work: the plain heats, the air climbs the wall, and the range becomes a conveyor belt of lift.",
         "In winter the snow line drops to the ridges above launch and the meadows at Billing go white."],
   rel:["bir-billing","great-himalayan-np","dharamshala"]},
  {id:"dharamshala", t:3, dom:"heritage", lat:32.24, lon:76.32, name:"Dharamshala and McLeod Ganj", place:"Himachal Pradesh, India",
   hook:"Home of the Dalai Lama since 1960, and the turnpoint of the classic run.",
   body:["The Tibetan government in exile settled above Dharamshala in the hill station of McLeod Ganj, and the town is now a mix of monasteries, trekkers and Tibetan cafes. From the air the Tsuglagkhang temple complex is the landmark that tells you the turnpoint is near."],
   rel:["bir-dharamshala-run","sherabling"]},
  {id:"sherabling", t:3, dom:"heritage", lat:32.0, lon:76.7, name:"Palpung Sherabling", place:"Bir, India",
   hook:"A monastery in the pine forest under the landing field.",
   body:["Bir is a Tibetan settlement, founded by refugees in the 1960s, and Palpung Sherabling is its largest monastery, set in forest a few kilometres from the landing. Hundreds of monks study here. The morning chanting carries up to the landing field on still days.",
         "Landing etiquette matters here. The field is next to a village that has been kind enough to host pilots for forty years."],
   rel:["bir-billing","dharamshala"]},
  {id:"kangra-fort", t:3, dom:"heritage", lat:32.09, lon:76.25, name:"Kangra Fort", place:"Kangra, India",
   hook:"One of the oldest forts in India, and a thermal trigger when the day is weak.",
   body:["Kangra Fort has stood on its rock spur above the Banganga river for well over a thousand years, long enough to have been looted by Mahmud of Ghazni in 1009 and shaken down by the 1905 earthquake. The dark rock and the river gorge below it warm early and give pilots a reliable climb on the plains leg."],
   rel:["dhauladhar","bir-dharamshala-run"]},
  {id:"great-himalayan-np", t:2, dom:"nature", lat:31.8, lon:77.5, name:"Great Himalayan National Park", place:"Kullu, India, UNESCO World Heritage",
   hook:"Snow leopards, blue sheep and 375 bird species above the Kullu valley.",
   body:["The park runs from 1,500 m to over 6,000 m and protects the upper catchments of four rivers. Its western Himalayan forests and alpine meadows are a UNESCO site for the sheer density of species, including the western tragopan and the Himalayan tahr.",
         "No flying inside the park. It is a reminder of what sits one valley east of Billing."],
   rel:["dhauladhar","himalayan-griffon"]},
  {id:"himalayan-griffon", t:3, dom:"nature", hidden:true, lat:32.1, lon:76.8, name:"Himalayan griffon", place:"Dhauladhar range, India",
   hook:"Nearly three metres of wingspan, and it never flaps if it can help it.",
   body:["The Himalayan griffon is one of the largest Old World vultures and the one you will share Billing thermals with. It climbs in the same cores you do, often above you, and when it leaves on glide you can trust the direction.",
         "A griffon thermalling tight and low in front of launch is the most reliable sign that the day has started."],
   rel:["bir-billing","ruppells-vulture","bar-headed-goose"]},
  {id:"bar-headed-goose", t:3, dom:"nature", hidden:true, lat:31.95, lon:76.1, name:"Bar-headed goose", place:"Pong Dam wetland, India",
   hook:"Crosses the Himalaya twice a year at over 7,000 m.",
   body:["Every winter tens of thousands of bar-headed geese land on the Pong Dam reservoir below Kangra, having flown from Mongolia and Tibet straight over the main Himalayan chain. Birds have been tracked above 7,000 m with oxygen levels that would put a human into a coma.",
         "The Trails layer draws their crossing. It is the most impressive cross country flight on this globe and no human has done it unpowered."],
   rel:["himalayan-griffon","bir-billing"]},
  {id:"taj-mahal", t:2, dom:"heritage", lat:27.17, lon:78.04, name:"Taj Mahal", place:"Agra, India, UNESCO World Heritage",
   hook:"A marble tomb built for one person, visited by eight million a year.",
   body:["Completed around 1653 by the Mughal emperor Shah Jahan for his wife Mumtaz Mahal. The white marble changes colour through the day, pink at dawn, white at noon, gold in the evening. Airspace over it is closed, so this one stays on the ground."],
   rel:["kangra-fort"]},
  {id:"kalka-shimla", t:3, dom:"heritage", lat:31.1, lon:77.17, name:"Kalka to Shimla railway", place:"Himachal Pradesh, India, UNESCO World Heritage",
   hook:"96 km, 102 tunnels and 864 bridges on a track 76 cm wide.",
   body:["A narrow gauge line opened in 1903 to haul the British summer government up to Shimla. It climbs 1,400 m through the Shivalik foothills and is still running. For a pilot the Shimla ridges are a different kind of flying, lower and wooded, with the big mountains a day further north."],
   rel:["dhauladhar"]},
  {id:"allahabad-airmail", t:3, dom:"aviation", lat:25.44, lon:81.85, name:"The world's first official airmail", place:"Allahabad, India, 1911",
   hook:"6,500 letters, 10 km, one Humber biplane.",
   body:["On 18 February 1911 the French pilot Henri Pequet flew a Humber Sommer biplane from an exhibition ground at Allahabad across the Ganges to Naini, carrying mail. It was the first airmail flight officially recognised anywhere in the world, and it took thirteen minutes."],
   rel:["lindbergh","kitty-hawk"]},

  // ---------- WORLD ----------
  {id:"mieussy", t:1, dom:"site", lat:46.14, lon:6.46, name:"Mieussy, birthplace of paragliding", place:"Haute Savoie, France", alt:"Pertuiset takeoff 1,450 m",
   hook:"In 1978 three friends ran off a hill under skydiving canopies.",
   body:["On 27 June 1978 Jean Claude Betemps, Andre Bohn and Gerard Bosson launched from the Pertuiset slope above Mieussy under modified parachutes and glided to the football pitch below. That flight is counted as the start of the sport.",
         "The village still flies the slope, and the Alps around it hold more flying sites per valley than anywhere else on earth."],
   fly:{window:"N to NE (340 to 060)",max:"20 km/h at takeoff",season:"Apr to Oct",sample:{wind:8,dir:20,gust:14,base:"2,600 m",verdict:"go",why:"Light and on the hill. Expect a mellow morning and a stronger afternoon."}},
   rel:["foehn","lilienthal","montgolfier"]},
  {id:"foehn", t:2, dom:"nature", hidden:true, lat:47.0, lon:11.0, name:"The Foehn", place:"The Alps",
   hook:"A warm wind that empties the sky in an hour.",
   body:["Foehn is the dry warm wind that pours down the lee side of the Alps when a pressure difference pushes air over the range. It arrives with a lens shaped cloud over the peaks and strong, turbulent, unflyable air below. Every Alpine pilot learns to read the sky for it before anything else."],
   rel:["mieussy","morning-glory"]},
  {id:"lilienthal", t:2, dom:"aviation", lat:52.43, lon:13.32, name:"Otto Lilienthal", place:"Berlin, Germany",
   hook:"Over 2,000 glides from a hill he built himself, 1891 to 1896.",
   body:["Lilienthal was the first person to make repeated, controlled, photographed flights, launching from a 15 m artificial hill at Lichterfelde under cambered wings of willow and cotton. He steered by shifting his weight, which is exactly what you do on a paraglider today.",
         "He died after a stall in 1896. His last words are usually given as: sacrifices must be made. The Wright brothers said his data started their work."],
   rel:["kitty-hawk","mieussy"]},
  {id:"kitty-hawk", t:1, dom:"aviation", lat:36.02, lon:-75.67, name:"Kitty Hawk, 1903", place:"Outer Banks, North Carolina, USA",
   hook:"Twelve seconds, 37 metres, and the world changed.",
   body:["The Wright brothers picked the dunes at Kill Devil Hills for soft sand and steady wind. On 17 December 1903 Orville flew the Flyer for 12 seconds, and by the fourth flight that day Wilbur stayed up for 59 seconds. They had spent three years gliding off the same dunes first.",
         "The dunes are still flown. Jockey's Ridge, a few kilometres south, is the busiest hang gliding school in the world."],
   rel:["lilienthal","lindbergh"]},
  {id:"lindbergh", t:1, dom:"aviation", lat:40.63, lon:-73.78, name:"Lindbergh, 1927", place:"New York to Paris",
   hook:"33 hours alone across the Atlantic in a plane with no front window.",
   body:["Charles Lindbergh left Roosevelt Field on Long Island on 20 May 1927 and landed at Le Bourget outside Paris 33 and a half hours later, the first solo non stop Atlantic crossing. The Spirit of St Louis had its fuel tank in front of the cockpit, so he looked out through a periscope.",
         "The Trails layer draws the great circle. He flew close to it by dead reckoning."],
   rel:["beryl-markham","kitty-hawk"]},
  {id:"montgolfier", t:2, dom:"aviation", lat:45.24, lon:4.67, name:"The first balloon", place:"Annonay, France, 1783",
   hook:"A paper lined bag, a fire of straw and wool, and 2,000 m of altitude.",
   body:["On 4 June 1783 the Montgolfier brothers sent an unmanned hot air balloon over the market square at Annonay. By November a man was aloft over Paris. For the first time in history a human being left the ground on purpose and came back."],
   rel:["lilienthal","mieussy"]},
  {id:"leonardo", t:2, dom:"heritage", lat:43.77, lon:11.26, name:"Leonardo's flying machines", place:"Florence, Italy",
   hook:"Five hundred years of drawings of wings that never flew.",
   body:["Leonardo da Vinci filled notebooks with ornithopters, a helical screw and a parachute design that was finally built and tested in 2000. It worked. He studied birds for decades and wrote that the bird is an instrument working according to mathematical law, which a human could reproduce."],
   rel:["icarus","lilienthal"]},
  {id:"icarus", t:2, dom:"heritage", lat:37.6, lon:26.2, name:"Icaria", place:"Aegean Sea, Greece",
   hook:"The island named for the boy who flew too close to the sun.",
   body:["In the myth Daedalus built wings of feathers and wax for himself and his son to escape Crete. Icarus climbed too high, the wax melted, and he fell into the sea near this island, which took his name. It is the oldest flying story in the Western world and the oldest warning about altitude."],
   rel:["leonardo","montgolfier"]},
  {id:"weifang", t:2, dom:"heritage", lat:36.7, lon:119.1, name:"Weifang, the kite capital", place:"Shandong, China",
   hook:"Kites were flown here 2,000 years before anyone flew a wing.",
   body:["China was flying kites by the 5th century BC, for signalling, measuring distance and, according to some accounts, lifting men to spy on enemy positions. Weifang holds the world's largest kite festival every April. A kite is a tethered wing, and a wing on a string is a paraglider that has not been let go."],
   rel:["leonardo","icarus"]},
  {id:"morning-glory", t:1, dom:"nature", lat:-17.74, lon:139.55, name:"The Morning Glory cloud", place:"Burketown, Queensland, Australia",
   hook:"A rolling cloud 1,000 km long that glider pilots surf like a wave.",
   body:["Every September and October a wave cloud forms over the Gulf of Carpentaria and rolls inland at dawn, sometimes several in a row, each up to 1,000 km long. Glider pilots fly here just to soar the front of it. It is the most predictable soaring cloud on the planet and almost nobody has heard of it."],
   rel:["foehn","albatross"]},
  {id:"albatross", t:2, dom:"nature", hidden:true, lat:-50.0, lon:60.0, name:"The wandering albatross", place:"Southern Ocean",
   hook:"Flies for months without landing and barely flaps.",
   body:["With a 3.5 m wingspan the wandering albatross uses dynamic soaring, dipping into the slow air near the waves and climbing into the fast air above, extracting energy from the wind gradient. It can cover 15,000 km on a single foraging trip. RC glider pilots have copied the technique to fly at over 800 km/h."],
   rel:["morning-glory","ruppells-vulture"]},
  {id:"gibraltar", t:2, dom:"nature", hidden:true, lat:36.0, lon:-5.6, name:"Strait of Gibraltar crossing", place:"Spain to Morocco",
   hook:"Half a million soaring birds funnel through 14 km of sea each autumn.",
   body:["Storks, eagles and vultures cannot thermal over water, so they wait at Tarifa for a tailwind and glide the strait in one go. On a good September day you can watch thousands cross. The flying sites at Tarifa and Algodonales share the same air, and the same wind problem."],
   rel:["ruppells-vulture","bar-headed-goose"]}
];

// Illustrative trails. Each: id, name, kind, points [lat, lon]. gc:true draws a great circle between first and last point.
window.ATLAS_TRAILS = [
  {id:"lindbergh", name:"Lindbergh 1927, New York to Paris", pts:[[40.63,-73.78],[48.97,2.44]], gc:true},
  {id:"beryl-markham", name:"Markham 1936, Abingdon to Nova Scotia", pts:[[51.7,-1.3],[46.3,-60.3]], gc:true},
  {id:"bar-headed-goose", name:"Bar-headed goose migration, Mongolia to Pong Dam", pts:[[47.0,105.0],[31.95,76.1]], gc:true},
  {id:"bir-dharamshala-run", name:"Billing to Dharamshala and back", pts:[[32.04,76.73],[32.10,76.60],[32.14,76.50],[32.20,76.40],[32.24,76.32],[32.18,76.45],[32.09,76.62],[32.04,76.73]]},
  {id:"elgeyo-run", name:"The escarpment run, Kessup north", pts:[[0.61,35.54],[0.80,35.57],[1.00,35.60],[1.20,35.62],[1.40,35.64],[1.20,35.60],[0.90,35.56],[0.61,35.54]]}
];

// ---------- Added in build 2: more world pins, Kazakhstan, Peru, knowledge, hidden finds ----------
window.ATLAS_ENTRIES.push(
  // Kazakhstan (tour June 2027)
  {id:"almaty-site", t:1, dom:"site", lat:43.16, lon:77.08, name:"Almaty, Tian Shan foothills", place:"Kazakhstan", alt:"Takeoff 1,800 to 2,200 m above the city", icon:"wing",
   hook:"A 7,000 m range standing over a city of two million.",
   body:["The Zailiysky Alatau rises straight out of Almaty. Takeoffs on the foothills above the city give you the plains to the north and the glaciated Tian Shan to the south, with the summer thermals of a continental climate.",
         "My Kazakhstan tour is planned for June 2027. This pin will grow as the recce comes together."],
   fly:{window:"N to NW (320 to 020)",max:"25 km/h at takeoff",season:"May to Sep",sample:{wind:12,dir:350,gust:18,base:"4,200 m",verdict:"go",why:"Northerly up the foothills, high base, a strong continental day."}},
   season:[0,0,1,2,4,5,5,5,4,2,0,0], rel:["charyn-canyon","tamgaly","khan-tengri"]},
  {id:"charyn-canyon", t:2, dom:"nature", lat:43.35, lon:79.08, name:"Charyn Canyon", place:"Kazakhstan", icon:"mountain",
   hook:"A 150 km red rock canyon, cousin of the Grand Canyon.",
   body:["The Charyn river has cut a canyon up to 300 m deep through red sandstone east of Almaty. The Valley of Castles section has rock towers that glow at sunset. Flyable? Launches have been attempted from the rim. Treat it as a place to visit on a rest day."],
   rel:["almaty-site"]},
  {id:"tamgaly", t:3, dom:"heritage", lat:43.8, lon:75.53, name:"Tamgaly petroglyphs", place:"Kazakhstan, UNESCO World Heritage", icon:"pot",
   hook:"5,000 rock carvings, including sun headed gods, from the Bronze Age.",
   body:["In a gorge north west of Almaty, around 5,000 petroglyphs cover the rock faces, the oldest from the 14th century BC. Among them are figures with sun shaped heads, hunting scenes and animals now gone from the steppe."],
   rel:["almaty-site"]},
  {id:"khan-tengri", t:3, dom:"nature", hidden:true, lat:42.21, lon:80.17, name:"Khan Tengri", place:"Tian Shan, Kazakhstan and Kyrgyzstan", icon:"mountain",
   hook:"A 7,010 m marble pyramid that turns red at sunset.",
   body:["The Lord of the Sky, the highest point in Kazakhstan, is a near perfect pyramid of marble. The name is the same wind and sky god the ancient Turkic peoples worshipped. For pilots it marks the edge of the flyable world here."],
   rel:["almaty-site"]},
  {id:"baikonur", t:2, dom:"aviation", lat:45.92, lon:63.34, name:"Baikonur Cosmodrome", place:"Kazakhstan", icon:"rocket",
   hook:"Where the first human left the planet, 12 April 1961.",
   body:["Yuri Gagarin launched from Site 1 at Baikonur and orbited the earth once in 108 minutes. The same pad launched Sputnik in 1957. It is still the busiest launch site on earth and still leased by Russia from Kazakhstan.",
         "The highest flight any pin on this globe can claim."],
   rel:["almaty-site","kitty-hawk"]},

  // Peru (tour November 2027)
  {id:"sacred-valley", t:1, dom:"site", lat:-13.33, lon:-72.08, name:"Sacred Valley", place:"Cusco, Peru", alt:"Takeoffs 3,700 to 4,200 m", icon:"wing",
   hook:"Launch at 4,000 m over Inca terraces and land next to a 500 year old wall.",
   body:["The Urubamba valley between Cusco and Machu Picchu is the highest regular paragliding I run. Takeoffs sit on the valley rim above Chinchero and Urubamba, with glaciated peaks around and the valley floor 1,000 m below.",
         "My Peru tour is planned for November 2027. Altitude is the first thing to plan for here, before the wing."],
   fly:{window:"E to SE (070 to 140)",max:"22 km/h at takeoff",season:"Apr to Nov",sample:{wind:9,dir:100,gust:15,base:"5,400 m",verdict:"go",why:"Light valley breeze and a base above the ridges. Thin air, long takeoff runs."}},
   season:[1,0,0,2,4,5,5,5,5,4,3,2], rel:["machu-picchu","nazca-lines","andean-condor","lake-titicaca"]},
  {id:"machu-picchu", t:2, dom:"heritage", lat:-13.16, lon:-72.55, name:"Machu Picchu", place:"Peru, UNESCO World Heritage", icon:"ruin",
   hook:"A royal estate on a ridge, abandoned before the Spanish found it.",
   body:["Built around 1450 for the Inca emperor Pachacuti and left within a century. The site sits on a saddle at 2,430 m between two peaks with the Urubamba looping 400 m below on three sides. Airspace is closed. You will see it from the ground, like everyone else."],
   rel:["sacred-valley"]},
  {id:"nazca-lines", t:2, dom:"heritage", lat:-14.74, lon:-75.13, name:"Nazca Lines", place:"Peru, UNESCO World Heritage", icon:"pot",
   hook:"Drawings 300 m long that only make sense from the air.",
   body:["Between 500 BC and 500 AD the Nazca people scraped the dark desert surface to expose pale ground beneath, drawing a hummingbird, a monkey, a spider and hundreds of straight lines. Nobody saw them whole until aircraft flew over in the 1920s. Light aircraft tours circle them today."],
   rel:["sacred-valley","andean-condor"]},
  {id:"andean-condor", t:3, dom:"nature", hidden:true, lat:-15.6, lon:-71.9, name:"Andean condor", place:"Colca Canyon, Peru", icon:"bird",
   hook:"Flaps once an hour. Weighs as much as a small child.",
   body:["The condor has the largest wing area of any bird, a 3.3 m span, and a body up to 15 kg. It cannot afford to flap. At Colca Canyon the condors leave their roosts mid morning as the first thermals rise off the cliffs, which is also when the paragliders launch at Cruz del Condor."],
   rel:["sacred-valley","ruppells-vulture","albatross"]},
  {id:"lake-titicaca", t:3, dom:"nature", lat:-15.9, lon:-69.4, name:"Lake Titicaca", place:"Peru and Bolivia", icon:"wave",
   hook:"The highest navigable lake on earth, at 3,812 m.",
   body:["A lake the size of a small country, with floating islands built from reeds by the Uros people, who have lived on the water for centuries. The lake breeze builds every afternoon and is strong enough to shut down flying on the surrounding hills."],
   rel:["sacred-valley"]},

  // World aviation and nature, round two
  {id:"annecy", t:2, dom:"site", lat:45.82, lon:6.23, name:"Annecy, Col de la Forclaz", place:"Haute Savoie, France", alt:"Takeoff 1,250 m, landing by the lake", icon:"wing",
   hook:"Probably the busiest takeoff in the world, over a turquoise lake.",
   body:["On a summer afternoon more than a hundred wings can be in the air above Lake Annecy. The lake breeze is gentle and reliable, the landing at Doussard is a mown field, and the view is the reason half of all pilots started."],
   fly:{window:"W to NW (250 to 330)",max:"22 km/h at takeoff",season:"Apr to Oct",sample:{wind:10,dir:290,gust:14,base:"2,400 m",verdict:"go",why:"The lake breeze is in and smooth. A standard Forclaz afternoon."}},
   season:[0,0,1,3,4,5,5,5,4,3,1,0], rel:["mieussy","foehn"]},
  {id:"oludeniz", t:2, dom:"site", lat:36.52, lon:29.14, name:"Oludeniz, Babadag", place:"Turkey", alt:"Takeoff 1,700 or 1,900 m, landing on the beach", icon:"wing",
   hook:"Launch from a 1,900 m mountain and land on the beach you can see from the top.",
   body:["Babadag rises straight out of the Mediterranean above the blue lagoon of Oludeniz. A road runs to the takeoffs, the sea breeze fills in by late morning, and the landing is a promenade next to the sand. Thousands of tandem flights a season."],
   fly:{window:"S to SW (170 to 240)",max:"24 km/h at takeoff",season:"Apr to Nov",sample:{wind:13,dir:210,gust:17,base:"2,200 m",verdict:"go",why:"Sea breeze straight up the face. Expect traffic."}},
   season:[0,0,1,3,5,5,5,5,5,4,2,0], rel:["icarus","gibraltar"]},
  {id:"interlaken", t:3, dom:"site", lat:46.69, lon:7.86, name:"Interlaken, Beatenberg", place:"Switzerland", alt:"Takeoff 1,500 m, landing in town", icon:"wing",
   hook:"Two lakes, three 4,000 m peaks, and a landing field in the middle of town.",
   body:["Beatenberg takeoff looks across to the Eiger, Monch and Jungfrau. Flights land on the Hohematte, a park in the centre of Interlaken, which is why every tourist in the town has watched a paraglider land."],
   rel:["annecy","foehn"]},
  {id:"pokhara", t:1, dom:"site", lat:28.25, lon:83.9, name:"Pokhara, Sarangkot", place:"Nepal", alt:"Takeoff 1,600 m, landing by Phewa lake", icon:"wing",
   hook:"Thermal with vultures while an 8,000 m peak fills the sky.",
   body:["Sarangkot hill above Pokhara gives you Annapurna and Machapuchare straight ahead and Phewa lake below. The valley is warm, the thermals are gentle in the morning and strong by noon, and the vultures here have been trained to fly with pilots in what is called parahawking.",
         "The next big site along the Himalaya west of Bir. Many pilots do both in one trip."],
   fly:{window:"S to SW (160 to 230)",max:"22 km/h at takeoff",season:"Oct to Apr",sample:{wind:9,dir:190,gust:14,base:"2,900 m",verdict:"go",why:"Gentle valley wind and a base above Sarangkot. Textbook."}},
   season:[4,5,5,3,1,0,0,0,1,4,5,5], rel:["bir-billing","himalayan-griffon","everest-flight"]},
  {id:"everest-flight", t:3, dom:"aviation", hidden:true, lat:27.99, lon:86.93, name:"Paragliding off Everest", place:"Nepal", icon:"wing",
   hook:"In 2011 two pilots launched from 8,848 m and flew for 42 minutes.",
   body:["Sano Babu Sunuwar and Lakpa Tsheri Sherpa took off from the summit of Everest on 21 May 2011 under a tandem wing, landed at Namche Bazaar, then kayaked to the Bay of Bengal. The highest paraglider launch ever made. It will almost certainly stay that way."],
   rel:["pokhara","bar-headed-goose"]},
  {id:"valle-de-bravo", t:2, dom:"site", lat:19.19, lon:-100.13, name:"Valle de Bravo", place:"Mexico", alt:"El Penon takeoff 2,300 m", icon:"wing",
   hook:"The winter escape of the world's best pilots.",
   body:["From November to March the highlands west of Mexico City give strong, dry, reliable thermals every day. The World Cup has come here many times. The flying is high, the air is thin and the cloudbase often sits above 4,000 m."],
   season:[5,5,4,2,0,0,0,0,0,2,4,5], rel:["sacred-valley"]},
  {id:"manilla", t:2, dom:"site", lat:-30.74, lon:150.65, name:"Manilla, Mount Borah", place:"New South Wales, Australia", alt:"Takeoffs on all four sides, 900 m", icon:"wing",
   hook:"A hill you can launch from whichever way the wind blows.",
   body:["Mount Borah has takeoffs facing every direction, which is why it hosted the paragliding World Championships in 2007. Flat land in all directions means the big flights go on until the sun drops. The Australian open distance records live around here."],
   season:[5,4,3,2,1,0,0,0,2,4,5,5], rel:["morning-glory","albatross"]},
  {id:"quixada", t:2, dom:"site", lat:-4.97, lon:-39.02, name:"Quixada", place:"Ceara, Brazil", alt:"Takeoff 400 m on a granite dome", icon:"wing",
   hook:"Where the 500 km paragliding flights happen.",
   body:["The trade wind blows across the dry Brazilian sertao from the same direction every day from October to December. Pilots launch off a granite dome at dawn and fly downwind all day. The open distance world record, over 600 km, was set here in 2021."],
   season:[0,0,0,0,0,0,0,1,3,5,5,4], rel:["manilla","kerio-valley"]},
  {id:"dune-du-pilat", t:3, dom:"site", lat:44.59, lon:-1.21, name:"Dune du Pilat", place:"Arcachon, France", alt:"110 m sand dune", icon:"wing",
   hook:"The tallest sand dune in Europe, soared in a sea breeze.",
   body:["A 110 m wall of sand facing the Atlantic. The west wind hits it and goes straight up, so pilots soar back and forth for hours a few metres above the sand. The gentlest introduction to ridge flying anywhere, and one of the most photographed."],
   rel:["annecy","gibraltar"]},
  {id:"gagarin-landing", t:3, dom:"aviation", hidden:true, lat:51.27, lon:45.99, name:"Gagarin's landing field", place:"Saratov, Russia", icon:"rocket",
   hook:"He parachuted into a potato field and asked a farmer for a phone.",
   body:["Gagarin ejected from Vostok 1 at 7 km, as planned, and came down under his own parachute near the village of Smelovka. The first people he met were a woman and her granddaughter planting potatoes, who asked if he had come from outer space. He said yes."],
   rel:["baikonur"]},
  {id:"amelia-earhart", t:2, dom:"aviation", lat:-0.1, lon:-176.6, name:"Amelia Earhart's last position", place:"Near Howland Island, Pacific", icon:"plane",
   hook:"Her radio was heard until 8.43 am on 2 July 1937. Then nothing.",
   body:["Earhart and navigator Fred Noonan were trying to find Howland Island, a strip of coral two kilometres long, after a 4,000 km leg from New Guinea. The coastguard cutter Itasca heard her but could not get a bearing. The Electra was never found. The search continues."],
   rel:["lindbergh","beryl-markham"]},
  {id:"bleriot", t:3, dom:"aviation", lat:50.97, lon:1.85, name:"Bleriot crosses the Channel", place:"Calais to Dover, 1909", icon:"plane",
   hook:"37 minutes, no compass, and the island was never the same.",
   body:["Louis Bleriot flew his monoplane from Les Baraques near Calais to a field above Dover on 25 July 1909, winning a newspaper prize of 1,000 pounds. He had no compass and followed a ship. In London the papers said England was no longer an island."],
   rel:["lindbergh","montgolfier"]},
  {id:"red-bull-x-alps", t:2, dom:"aviation", lat:47.8, lon:13.04, name:"Red Bull X-Alps", place:"Salzburg to Monaco", icon:"wing",
   hook:"1,200 km across the Alps by paraglider and on foot. Nothing else allowed.",
   body:["Every two years around thirty athletes race from Salzburg to Monaco carrying their wings, flying when they can and hiking when they cannot, with a few hours of sleep a night. The winners finish in under a week. It is the hardest adventure race in the world and the sport's answer to the Tour de France.",
         "The Trails layer draws the rough line."],
   rel:["mieussy","annecy","interlaken"]},
  {id:"wright-dayton", t:3, dom:"aviation", lat:39.76, lon:-84.19, name:"The Wright bicycle shop", place:"Dayton, Ohio, USA", icon:"plane",
   hook:"The Flyer was built here, between repairing bicycles.",
   body:["Orville and Wilbur ran a bicycle business in Dayton and built their gliders and the 1903 Flyer in the shop's back room. The wind tunnel they built in 1901 to correct Lilienthal's lift tables was a wooden box with a fan. It changed everything."],
   rel:["kitty-hawk","lilienthal"]},
  {id:"zeppelin", t:3, dom:"aviation", lat:47.65, lon:9.48, name:"Friedrichshafen and the Zeppelins", place:"Lake Constance, Germany", icon:"balloon",
   hook:"Airships 245 m long once crossed the Atlantic from this lake.",
   body:["Count Zeppelin flew his first rigid airship from a floating hangar on Lake Constance in 1900. By the 1930s the Graf Zeppelin had circled the world and crossed the Atlantic over a hundred times. The Hindenburg fire in 1937 ended it in 34 seconds."],
   rel:["montgolfier","bleriot"]},
  {id:"birdman-rally", t:4, dom:"heritage", hidden:true, lat:50.81, lon:-1.09, name:"The birdman of Bognor", place:"Bognor Regis, England", icon:"wing",
   hook:"People jump off a pier in homemade wings. Most reach the water.",
   body:["Since 1971 competitors have launched from the end of a seaside pier in anything from feathered suits to proper hang gliders, trying to glide 100 m for a cash prize. Almost nobody makes it. The sport's sense of humour, kept alive on the south coast of England."],
   rel:["lilienthal","icarus"]},
  {id:"hawaii-makapuu", t:3, dom:"site", hidden:true, lat:21.31, lon:-157.66, name:"Makapuu, Oahu", place:"Hawaii, USA", icon:"wing",
   hook:"Trade wind soaring above the Pacific, 365 days a year.",
   body:["The cliffs on the windward side of Oahu catch the trade wind almost every day of the year. Pilots soar the ridge above the sea with turtles and whales below. The site is also where hang gliding found its feet in the 1970s."],
   rel:["dune-du-pilat","albatross"]},
  {id:"serengeti-balloon", t:3, dom:"aviation", hidden:true, lat:-2.33, lon:34.83, name:"Dawn balloons over the Serengeti", place:"Tanzania", icon:"balloon",
   hook:"The oldest way to fly, over the oldest landscape.",
   body:["Hot air balloons launch at first light over the central Serengeti and drift with the morning breeze above the herds. It is the only legal way to fly over the park, and a good reminder of what thermal air does to a balloon once the sun gets up: nothing good."],
   rel:["maasai-mara","montgolfier"]},

  // Knowledge pins: the encyclopedia starts here, each anchored where it is best understood
  {id:"k-thermal", t:3, dom:"knowledge", lat:0.5, lon:35.45, name:"What is a thermal?", place:"Explained over the Kerio Valley", icon:"book",
   hook:"A bubble of warm air that leaves the ground and keeps rising until it cools.",
   body:["The sun heats the ground unevenly. A dark field, a rock face or a town warms faster than the forest next to it, and the air above it becomes lighter than the air around it. Once it is light enough it breaks away and rises, like a bubble in water.",
         "A paraglider circles inside that bubble to stay in it. The bubble rises until its temperature matches the air around it, which is roughly where the cloud forms. That is cloudbase."],
   rel:["k-cloudbase","kerio-valley","ruppells-vulture"]},
  {id:"k-cloudbase", t:3, dom:"knowledge", lat:32.2, lon:76.9, name:"What is cloudbase?", place:"Explained over the Dhauladhar", icon:"book",
   hook:"The height where rising air gets cold enough for its water to condense.",
   body:["Air cools as it rises, about one degree for every 100 m. At some height it reaches the temperature where the water vapour in it turns into droplets, and a cloud forms. That flat bottom you see on every cumulus is the same height for every thermal in the area that day.",
         "Pilots care because cloudbase is the ceiling. A high base means long glides between climbs. A low base means short hops and a cautious day."],
   rel:["k-thermal","bir-billing"]},
  {id:"k-window", t:3, dom:"knowledge", lat:46.0, lon:6.35, name:"What is a wind window?", place:"Explained over the Alps", icon:"book",
   hook:"The range of wind directions a takeoff can safely be flown in.",
   body:["Every takeoff faces a direction. Wind coming up the slope from that direction lets you inflate and launch cleanly and gives you lift on the hill. Wind from behind pushes you into the ground. Wind from the side makes the takeoff run a fight.",
         "The window is usually around 60 degrees either side of the direction the slope faces, narrower on a steep or tricky launch. Every site pin on this atlas carries its window."],
   rel:["mieussy","annecy","k-thermal"]},
  {id:"k-valley-breeze", t:3, dom:"knowledge", lat:45.9, lon:6.1, name:"Why does the valley wind arrive at eleven?", place:"Explained over Annecy", icon:"book",
   hook:"Because the mountains have been heating for four hours by then.",
   body:["Through the morning the slopes warm and the air on them rises. Something has to replace it, and that something is air pulled up the valley from the plains and lakes below. By late morning this becomes a steady wind blowing up every valley in the range, and it keeps building until late afternoon.",
         "It is predictable, which is why Alpine flying has a rhythm: launch early for calm air, or mid afternoon for the strongest thermals and the strongest valley wind. Not at one in the afternoon on a big day."],
   rel:["annecy","k-window","foehn"]},
  {id:"k-ippi", t:3, dom:"knowledge", lat:59.5, lon:10.9, name:"What is an IPPI card?", place:"Explained from home base", icon:"book",
   hook:"The international licence that lets your national rating travel.",
   body:["The IPPI card is issued by the FAI and translates your home country's pilot rating onto a scale from 1 to 5 that every country understands. IPPI 2 is a pilot cleared to fly on their own at known sites in good conditions. IPPI 3 adds thermalling and cross country.",
         "My tours ask for IPPI 2 or an equivalent national rating. Bring the card. Some sites will ask for it at the gate."],
   rel:["oslo-home","kerio-valley","bir-billing"]},
  {id:"k-sea-breeze", t:3, dom:"knowledge", lat:36.4, lon:29.0, name:"What is a sea breeze?", place:"Explained over Oludeniz", icon:"book",
   hook:"Land heats faster than water, so by noon the wind blows in from the sea.",
   body:["On a sunny morning the land warms quickly and the sea stays cool. Air rises over the land and the cooler sea air flows in to replace it, usually arriving at the coast between ten and noon and reaching 20 or 30 km inland by afternoon.",
         "Coastal sites like Oludeniz, Dune du Pilat and Makapuu are built on it. It is smooth, reliable and it switches off at sunset."],
   rel:["oludeniz","dune-du-pilat","k-valley-breeze"]}
);

window.ATLAS_TRAILS.push(
  {id:"red-bull-x-alps", name:"Red Bull X-Alps, Salzburg to Monaco (rough line)", pts:[[47.8,13.04],[47.07,12.69],[46.8,11.0],[46.5,9.8],[46.2,8.0],[46.0,7.1],[45.92,6.87],[45.6,6.6],[44.9,6.7],[44.1,7.1],[43.73,7.42]]},
  {id:"bleriot", name:"Bleriot 1909, Calais to Dover", pts:[[50.95,1.82],[51.13,1.34]]},
  {id:"amelia-earhart", name:"Earhart 1937, Lae to Howland (never completed)", pts:[[-6.73,147.0],[0.8,-176.6]], gc:true},
  {id:"quixada", name:"Quixada record line, downwind to the west (illustrative)", pts:[[-4.97,-39.02],[-5.3,-40.5],[-5.6,-42.0],[-5.9,-43.5]]}
);

// Seasonal pattern (typical month-by-month flyability, 0 to 5) for the earlier sites
Object.assign(window.ATLAS_ENTRIES.find(e=>e.id==="kerio-valley"),{season:[5,5,4,1,0,1,2,2,3,4,3,4],icon:"wing"});
Object.assign(window.ATLAS_ENTRIES.find(e=>e.id==="bir-billing"),{season:[1,1,4,5,4,1,0,0,2,5,5,2],icon:"wing"});
Object.assign(window.ATLAS_ENTRIES.find(e=>e.id==="mieussy"),{season:[0,0,1,3,4,5,5,5,4,3,1,0],icon:"wing"});

// Icons for the first batch
const ICONS={"oslo-home":"home","elgeyo-run":"wing","iten":"runner","great-rift-valley":"mountain","lake-turkana":"skull","mount-kenya":"mountain","hells-gate":"mountain","ruppells-vulture":"bird","maasai-mara":"wildebeest","lamu":"dhow","fort-jesus":"fort","gedi":"ruin","thimlich":"ruin","beryl-markham":"plane",
"bir-dharamshala-run":"wing","dhauladhar":"mountain","dharamshala":"temple","sherabling":"temple","kangra-fort":"fort","great-himalayan-np":"leaf","himalayan-griffon":"bird","bar-headed-goose":"goose","taj-mahal":"temple","kalka-shimla":"train","allahabad-airmail":"letter",
"foehn":"cloud","lilienthal":"wing","kitty-hawk":"plane","lindbergh":"plane","montgolfier":"balloon","leonardo":"scroll","icarus":"scroll","weifang":"kite","morning-glory":"cloud","albatross":"bird","gibraltar":"bird"};
window.ATLAS_ENTRIES.forEach(e=>{if(!e.icon)e.icon=ICONS[e.id]||(e.dom==="site"?"wing":e.dom==="aviation"?"plane":e.dom==="nature"?"leaf":"pot")});

// ---------- Build 3: content depth ----------
(function(){
const E=window.ATLAS_ENTRIES, by=id=>E.find(e=>e.id===id);
// "What you're flying over" bands on the sites
by("kerio-valley").over=[
 {k:"Geology",t:"The escarpment is the western wall of the Gregory Rift, a crack that opened around 25 million years ago. The valley floor keeps dropping a fraction of a millimetre a year. Hot springs along the base are the heat of the rift coming up."},
 {k:"History",t:"The Kerio Valley was a trade route between the highlands and Lake Turkana long before roads, carried on by the Marakwet, who still run irrigation furrows along the escarpment that are at least 300 years old."},
 {k:"Nature",t:"Below you the valley is dry thorn and acacia, the escarpment is wet forest with colobus monkeys, and the lip is farmland at 2,400 m. Ruppell's vultures and augur buzzards share the ridge lift."}];
by("kerio-valley").body.push("Landing is on the valley floor at Kessup or along the road, and the retrieve back up the escarpment is an hour. Carry water. The valley is 10 degrees warmer than takeoff and the afternoon is not kind.");
by("bir-billing").over=[
 {k:"Geology",t:"The Dhauladhar is the youngest front of the Himalaya, still rising a centimetre a year as India pushes under Asia. The 1905 Kangra earthquake, which killed 20,000 people, was that collision moving."},
 {k:"History",t:"Bir was a Gaddi shepherd village until Tibetan refugees settled it in the 1960s. The monasteries, the tea gardens below the landing and the colonial church at Baijnath are each a different century of the same valley."},
 {k:"Nature",t:"Launch is in rhododendron and oak forest at 2,400 m. Himalayan griffons nest on the crags above, and in winter bar-headed geese fill Pong Dam on the plains below."}];
by("bir-billing").body.push("The landing field at Chaugan is big and forgiving but the valley wind picks up by two. Land by then, or land at the alternative near the tea gardens and walk.");
by("sacred-valley").over=[
 {k:"Geology",t:"The Andes here are folded sediment and old volcanics pushed up by the Nazca plate diving under South America. The glaciers on Veronica and Salkantay are retreating fast."},
 {k:"History",t:"The valley floor was the Inca breadbasket. The terraces at Moray and the salt pans at Maras, both visible from the air, were engineered five centuries ago and still work."},
 {k:"Nature",t:"Condors still patrol the upper valley. Below 3,000 m the valley is eucalyptus and maize; above 4,000 m it is puna grassland and llamas."}];
by("almaty-site").over=[
 {k:"Geology",t:"The Zailiysky Alatau is granite pushed up where the Indian collision is still being felt 2,000 km away. The 1911 Kemin earthquake dropped whole hillsides into the valleys above the city."},
 {k:"History",t:"Almaty sits on the old Silk Road. The apple, Malus sieversii, was domesticated in these foothills, which is why the city's old name, Alma-Ata, means father of apples."},
 {k:"Nature",t:"Spruce forest to 2,800 m, then alpine meadow, then rock and ice. Snow leopards live in the valleys above the takeoffs, though you will not see one."}];
by("mieussy").over=[
 {k:"Geology",t:"The Pertuiset slope is limestone from an ancient sea floor, folded when Africa pushed into Europe. The Giffre valley below was cut by a glacier that reached here 20,000 years ago."},
 {k:"History",t:"Three skydivers in 1978, then a decade of homemade wings, then a sport. The village has a monument on the launch and a festival every June."},
 {k:"Nature",t:"Chamois on the cliffs, golden eagles on the thermals, and the Mont Blanc massif on the horizon to the east."}];
by("pokhara").over=[
 {k:"Geology",t:"The Pokhara valley is filled with debris from a catastrophic flood off Annapurna around 1,100 years ago, which is why the valley floor is flat and the Seti river runs in a gorge."},
 {k:"History",t:"A trading stop on the salt route between Tibet and India, then a Gurkha recruiting town, then the hippie trail, then the trekking capital of Nepal."},
 {k:"Nature",t:"Egyptian vultures and steppe eagles thermal with the gliders. The lake is the warm end of the valley; Machapuchare, the fishtail peak, is the cold end, and it is closed to climbing."}];
by("annecy").over=[
 {k:"Geology",t:"The lake is a glacial trough in folded limestone. The water is among the cleanest in Europe because the whole valley cleaned it up in the 1960s."},
 {k:"History",t:"The old town is medieval canals and a 12th century prison on an island. The Forclaz takeoff was a hay meadow until the 1980s."},
 {k:"Nature",t:"Griffon vultures returned to the Bauges range in the 2000s and now cross the lake. The lake breeze they use is the one you use."}];
by("oludeniz").over=[
 {k:"Geology",t:"Babadag is a block of limestone that fell toward the sea along a fault. The lagoon below is a sandbar closing off a drowned valley."},
 {k:"History",t:"The ghost town of Kayakoy sits behind the mountain, Greek until the 1923 population exchange, empty since. Lycian rock tombs are cut into the cliffs along the coast."},
 {k:"Nature",t:"Pine forest to the summit, loggerhead turtles on the beaches, and the Butterfly Valley, a slot canyon on the coast only reachable by boat or by air."}];

E.push(
 // Kenya, deeper
 {id:"olorgesailie", t:4, dom:"heritage", hidden:true, lat:-1.58, lon:36.45, name:"Olorgesailie hand axes", place:"Rift Valley, Kenya", icon:"pot",
  hook:"A lake bed littered with stone tools from a million years ago.",
  body:["The Leakeys found thousands of Acheulean hand axes here in 1942, lying where they were dropped beside a vanished lake. Nobody knows why so many were left in one place. Walk the boardwalk and they are still in the ground."], rel:["lake-turkana","thimlich"]},
 {id:"mount-elgon-caves", t:4, dom:"nature", hidden:true, lat:1.12, lon:34.55, name:"The elephant caves of Elgon", place:"Mount Elgon, Kenya and Uganda", icon:"mountain",
  hook:"Elephants walk deep into a mountain at night to mine salt with their tusks.",
  body:["Kitum cave on the Kenyan side of Mount Elgon runs 200 m into the volcano. Herds of elephants enter in the dark and gouge the walls for sodium. The cave has been widened by tusks over thousands of years."], rel:["mount-kenya","great-rift-valley"]},
 {id:"kakamega", t:3, dom:"nature", lat:0.29, lon:34.86, name:"Kakamega Forest", place:"Western Kenya", icon:"leaf",
  hook:"The last piece of the Congo rainforest left in Kenya.",
  body:["A 240 square kilometre fragment of the great central African forest, cut off when the climate dried. Four hundred bird species, blue monkeys, and butterflies by the thousand. It is forty minutes from Kerio on a rest day."], rel:["kerio-valley"]},
 {id:"wilson-airport", t:3, dom:"aviation", lat:-1.32, lon:36.81, name:"Wilson Airport", place:"Nairobi, Kenya", icon:"plane",
  hook:"The busiest airfield in East Africa, named after a woman who started it in 1929.",
  body:["Florence Kerr Wilson founded Wilson Airways in 1929 with one Gipsy Moth, and the airfield that took her name is still where every safari flight leaves from. Markham learned to fly here."], rel:["beryl-markham"]},
 {id:"chalbi", t:3, dom:"nature", lat:3.0, lon:37.5, name:"Chalbi Desert", place:"Northern Kenya", icon:"wave",
  hook:"A salt flat that was a lake 10,000 years ago.",
  body:["White and flat to the horizon, with camel caravans crossing to the wells at Kalacha. In the rains it floods a few centimetres deep and becomes a mirror. Flat ground, strong sun, and the most violent thermals in Kenya."], rel:["lake-turkana"]},
 // India, deeper
 {id:"spiti", t:3, dom:"nature", lat:32.25, lon:78.05, name:"Spiti Valley", place:"Himachal Pradesh, India", icon:"mountain",
  hook:"A cold desert at 4,000 m where monasteries sit on fossil sea beds.",
  body:["Behind the Dhauladhar and the Pir Panjal the rain stops and the land turns to brown rock and blue sky. Key monastery has stood above the Spiti river since the 11th century. The hills are full of ammonites from the Tethys sea."], rel:["dhauladhar","great-himalayan-np"]},
 {id:"pong-dam", t:3, dom:"nature", lat:31.95, lon:76.05, name:"Pong Dam wetland", place:"Kangra, India", icon:"wave",
  hook:"A reservoir that fills with 100,000 birds every winter.",
  body:["The Beas river was dammed in 1974 and the lake behind it became one of the most important wetlands in northern India. Bar-headed geese, cranes and pelicans winter here below the Dhauladhar. From Billing on a clear day you can see it."], rel:["bar-headed-goose","bir-billing"]},
 {id:"triund", t:3, dom:"nature", lat:32.27, lon:76.37, name:"Triund ridge", place:"Above McLeod Ganj, India", icon:"mountain",
  hook:"A 2,850 m meadow with the Dhauladhar wall standing in your face.",
  body:["A four hour walk from McLeod Ganj to a grass ridge with a 4,000 m wall of rock and snow across the valley. Pilots on the Dharamshala run pass over it. Walkers sleep on it under the stars."], rel:["dharamshala","bir-dharamshala-run"]},
 {id:"baijnath", t:4, dom:"heritage", hidden:true, lat:32.05, lon:76.65, name:"Baijnath temple", place:"Kangra, India", icon:"temple",
  hook:"A 13th century Shiva temple, five minutes from the landing field.",
  body:["Built in 1204 in the Nagara style with a tall curved spire, and still in use. The valley road from Bir passes it. The stone carvings have survived every earthquake since."], rel:["sherabling","kangra-fort"]},
 {id:"solang", t:3, dom:"site", lat:32.32, lon:77.16, name:"Solang Valley", place:"Manali, India", alt:"Takeoffs 2,500 to 3,000 m", icon:"wing",
  hook:"Short flights over snow in winter, big mountain air in summer.",
  body:["The valley above Manali is a ski slope in winter and a paragliding and zipline park in summer. Tandem flights by the hundred. Serious pilots use it as a staging point for the Rohtang and Spiti side."], rel:["bir-billing","spiti"]},
 // Kazakhstan, deeper
 {id:"big-almaty-lake", t:3, dom:"nature", lat:43.05, lon:76.98, name:"Big Almaty Lake", place:"Kazakhstan", icon:"wave",
  hook:"A turquoise lake at 2,500 m, half an hour above the city.",
  body:["A glacier-fed lake in a bowl of 4,000 m peaks that changes colour with the season. The valley above it holds an astronomical observatory and a cosmic ray station, built high for the thin air."], rel:["almaty-site"]},
 {id:"medeu", t:4, dom:"heritage", hidden:true, lat:43.16, lon:77.06, name:"Medeu skating rink", place:"Almaty, Kazakhstan", icon:"ruin",
  hook:"The highest skating rink in the world, where 120 speed records were set.",
  body:["Built at 1,691 m in a mountain gorge in 1951. The thin air and cold water made the ice fast enough that Soviet skaters broke record after record here. A cable car runs from the rink up to the Shymbulak ski area and the takeoffs."], rel:["almaty-site"]},
 // Peru, deeper
 {id:"colca", t:2, dom:"site", lat:-15.61, lon:-71.9, name:"Colca Canyon, Cruz del Condor", place:"Arequipa, Peru", alt:"Rim at 3,300 m, floor 1,200 m below", icon:"wing",
  hook:"Fly a canyon twice as deep as the Grand Canyon, with condors for company.",
  body:["The Colca is over 3,000 m deep in places. The condors launch from the cliffs below the Cruz del Condor viewpoint at mid morning, and pilots launch soon after. The terraces on the canyon walls were cut by the Collagua people before the Inca."], rel:["andean-condor","sacred-valley"]},
 {id:"lima-miraflores", t:3, dom:"site", lat:-12.13, lon:-77.03, name:"Lima, the Miraflores cliffs", place:"Peru", alt:"Cliff soaring at 70 m", icon:"wing",
  hook:"Soar a 70 m cliff in the middle of a city of ten million.",
  body:["The Pacific breeze hits the cliffs of the Costa Verde every afternoon and pilots soar above the parks and shopping malls of Miraflores, a few metres from office windows. It is the first and last flight of most Peru trips."], rel:["sacred-valley","dune-du-pilat"]},
 // Cross-country chains
 {id:"flyway-east-africa", t:2, dom:"nature", hidden:true, lat:9.0, lon:38.0, name:"The Rift Valley flyway", place:"Ethiopia to Kenya", icon:"bird",
  hook:"Millions of birds follow the rift south every autumn, using the same thermals pilots do.",
  body:["Storks, eagles and buzzards cross from Europe at Suez, follow the Red Sea and the Ethiopian highlands, and pour down the Rift Valley into Kenya between September and November. On a good day at Kerio you share the escarpment with hundreds of steppe eagles.",
        "The chain continues: Gibraltar, Suez, Ethiopia, Kerio. Find all four."], rel:["gibraltar","kerio-valley","ruppells-vulture"]},
 {id:"suez-crossing", t:3, dom:"nature", hidden:true, lat:30.0, lon:32.5, name:"Suez bottleneck", place:"Egypt", icon:"bird",
  hook:"Where half a million raptors squeeze between two seas.",
  body:["Soaring birds will not cross open water, so everything migrating between Europe and Africa funnels over the narrow land bridge at Suez. Counts of over a million birds a season have been made from the hills around the canal."], rel:["gibraltar","flyway-east-africa"]},
 {id:"jebel-hafeet", t:4, dom:"site", hidden:true, lat:24.06, lon:55.77, name:"Jebel Hafeet", place:"Al Ain, UAE", icon:"wing",
  hook:"A 1,200 m rock in the desert with a road to the top.",
  body:["A limestone mountain rising out of the sand on the Oman border, with 60 hairpins to the summit. Winter is the season. The desert thermals are brutal and the air is dry enough to crack lips in an hour. On the way between Europe and India, if you are flying that way."], rel:["oludeniz","bir-billing"]}
);
// extra seasons and icons
by("colca").season=[2,1,1,3,5,5,5,5,5,4,3,2];by("lima-miraflores").season=[5,5,5,4,3,2,2,2,3,4,5,5];by("solang").season=[1,1,2,4,5,4,2,2,4,5,4,2];
E.forEach(e=>{if(!e.icon)e.icon=e.dom==="site"?"wing":e.dom==="aviation"?"plane":e.dom==="nature"?"leaf":"pot"});
})();
