"""Content for the knowledge base category landing pages (the lighter layout).

generate_kb_pages.category_page() switches a category to kb_layout.landing()
when its slug has an entry here. Each entry needs:
  kicker (the category name), h1 (a pilot's question), lead, sub, seo_title
  (70 characters or fewer), seo_desc (70 to 165), hero_alt, series_heading,
  series_kicker, faq_heading, and faq: five {q, a, src:[(episode, chapter, who)]}.
Hero image: assets/images/kb-<slug>.jpg (2400x900) with a .webp beside it.

Rules, as for the series pages: paraphrase, no dashes, questions end in "?",
answers 55 to 70 words. Everything here comes from the published series pages
(and the chapters they cite), and no question repeats a series page FAQ.
Chapter links are validated at build time, like the series pages.
"""
from kb_editorial import *  # noqa: F401,F403  (episode slug constants)

# Two episodes the Flight Mechanics entry cites by literal slug.
TOM = "tom-lolies-explains-the-science-of-wing-design-and"
HELMUT = "helmut-schrempf-modernizing-siv-courses-how-this-new"

LANDING = {
    "core-series": {
        "kicker": "Core Series",
        "h1": "How Do Experienced Pilots Travel, Train and Live for Flying?",
        "lead": "Three series about people rather than physics: local pilots on flying their home sites, the pilots at the top of the sport on how they train and think, and pilots who built their lives around flying. Each is written from the episode transcripts, with every claim linked to its chapter.",
        "sub": "This comprehensive collection is divided into three main sections, each designed to inspire, equip, and build your understanding of free flight from the ground up.",
        "seo_title": "Travel, Train and Live to Fly: Core Series | Paragliding Atlas",
        "seo_desc": "Local pilots on their home sites, top racers on how they train and think, and pilots who built a life around flying: the Core Series of the Paragliding Atlas.",
        "hero_alt": "An abstract drawing: faint contour lines of hills with a single pilot's track looping up through thermals and gliding on between them",
        "series_heading": "The three series",
        "series_kicker": "Built from the episodes",
        "faq_heading": "Questions across these series",
        "faq": [
            {"q": "Is it worth hiring a local guide when you fly abroad?",
             "a": "Eddie Colfox thinks so. In his view a pilot with 100 to 300 hours is still a beginner, and with an experienced guide or a group you fly five hours a day instead of two, learn more and are safer. Chris Garcia builds his tours around local pilots for a similar reason: when the weather turns tricky or something goes wrong, locals know best what to do.",
             "src": [(EDDIE, "c4", "Eddie Colfox"), (CG, "c4", "Chris Garcia")]},
            {"q": "Do you need oxygen to paraglide at high altitude?",
             "a": "The guests differ. Antoine Girard recommends oxygen for pilots new to altitude: with less oxygen the brain slows down just as the wing speeds up, and at 8,000 metres a wing trims at about 60 km/h. Damien Lacaze does not carry it: after a week of acclimatisation, sleeping at 4,000 metres and walking higher by day, he finds flying at 6,000 to 6,500 metres fine.",
             "src": [(AG, "c8", "Antoine Girard"), (DL, "c12", "Damien Lacaze")]},
            {"q": "How many hours a year do the best paragliding pilots fly?",
             "a": "A lot. Maxime Pinot says pilots who set out from scratch to reach the World Cup typically fly 400 to 500 hours a year, though experienced pilots can fly less; he has flown between 250 and 450 a year for about 20 years. Honorin Hamard now flies about 500 hours a year, has around 8,000 in total, and flew more than 200 in each of his first years.",
             "src": [(MP, "c4", "Maxime Pinot"), (MP, "c12", "Maxime Pinot"), (HH, "c11", "Honorin Hamard"), (HH, "c2", "Honorin Hamard")]},
            {"q": "Can you make a living from paragliding?",
             "a": "Some of the guests do, in very different ways. Honorin Hamard is now a test pilot. Benjamin Jordan built his career by cutting his living costs to almost nothing for about ten years, in a converted school bus, so he could say yes to projects. Shams turned his dog's unplanned fame online into brand collaborations, and Chris Garcia started a paragliding tour company in 2023.",
             "src": [(HH, "c6", "Honorin Hamard"), (BJ, "c4", "Benjamin Jordan"), (SHAMS, "c9", "Shams"), (CG, "c2", "Chris Garcia")]},
            {"q": "How do experienced pilots decide not to fly?",
             "a": "By setting limits and keeping to them. Maxime Pinot tells the young pilots he trains that if a race would cancel the task, they do not fly. Honorin Hamard abandoned a record attempt after three frontal collapses downwind of a mountain, and went down to try another day. Damien Lacaze warns that in a storm, the moment you want to land is already too late.",
             "src": [(MP, "c7", "Maxime Pinot"), (HH, "c1", "Honorin Hamard"), (DL, "c11", "Damien Lacaze")]},
        ],
    },
    "competitions": {
        "kicker": "Competitions & Performance",
        "h1": "How Do You Race, Judge Risk and Keep a Clear Head in Paragliding?",
        "lead": "Three series for pilots who want to go further: how competitions are set and scored and how pilots climb the ranking, how experienced pilots decide when to push and when to stop, and the mental side of flying, with the tools around it.",
        "sub": "Take a tour into the thrilling world of racing paragliders and learn how to push your performance boundaries safely and effectively. Strategies, training techniques, and mindset from the pilots who have done it all.",
        "seo_title": "Racing, Risk and a Clear Head: Competitions | Paragliding Atlas",
        "seo_desc": "How paragliding competitions are scored, how experienced pilots judge risk and when to stop, and how to stay calm and focused in the air: three series in one place.",
        "hero_alt": "An abstract drawing: competition turnpoint cylinders of different sizes, with an orange optimised route touching the edge of each on its way to a goal line",
        "series_heading": "The three series",
        "series_kicker": "Built from the episodes",
        "faq_heading": "Questions across these series",
        "faq": [
            {"q": "Should you race flat out in your first paragliding competitions?",
             "a": "Not yet, says Joerg Ewald. Fly as far as you can first, because speed comes once the distance game works. Manfred Ruhmer separates the two kinds of risk a race asks you to take: losing the task is one, and flying where the landing options have gone is the other. The first is the sport; the second is the one to design out of your flying.",
             "src": [(GAP, "c12", "Joerg Ewald"), (MANFRED, "c6", "Manfred Ruhmer")]},
            {"q": "Which matters more for safety, SIV or active flying?",
             "a": "Each has its job. Subir Sidhu's point is that you will only recover a shape your glider has been in before, which is what SIV is for, and the earlier the better. Beni Kälin warns that a rehearsed stall does nothing for a big collapse ten metres above the ground: active flying, keeping the wing open in the first place, is the skill that counts there.",
             "src": [(SUBIR, "c8", "Subir Sidhu"), (META, "c9", "Beni Kälin")]},
            {"q": "How do you know when you are pushing too hard?",
             "a": "Start by asking why you are pushing, says Grant Smith: glory is a fine driver, but an accident in an ego battle is a meaningless one. Beni Kälin adds that more flying does not automatically mean more safety, because day after day of smooth air breeds overconfidence. A break makes flying feel fast again, and in his view that feeling is exactly the point.",
             "src": [(GRANT, "c9", "Grant Smith"), (DK, "c1", "Beni Kälin")]},
            {"q": "How should a paraglider be tested before you trust a review?",
             "a": "Where it is hard, says the reviewer Ziad Bassil: low, in turbulent air where you have to push on and turn, not in the strongest conditions or on the best day. That is where a high aspect ratio wing will not turn on a dime and the differences between wings show. He also points out that reflex resists collapse but has nothing to do with trim.",
             "src": [(ZIAD, "c4", "Ziad Bassil"), (ZIAD, "c9", "Ziad Bassil")]},
            {"q": "How do you learn from a flight that went wrong?",
             "a": "Look past the outcome, says Subir Sidhu. If you got away with a bad launch, an incident still happened, so ask what it was, why it happened and whether you knew. Will Gadd is blunt about clouds in particular: nobody gets sucked in, you flew into it. Own that decision, and you can fix it next time by leaving earlier and checking the radar.",
             "src": [(SUBIR, "c8", "Subir Sidhu"), (WILL, "c13", "Will Gadd")]},
        ],
    },
    "meteorology": {
        "kicker": "Meteorology & Weather Analysis",
        "h1": "What Do Paragliding Pilots Need to Know About Weather?",
        "lead": "One series so far, built around a real forecast walked through by a club weather briefer: why the apps disagree, how far ahead to trust them, wind at the height you fly, soundings and cloud base, and the local effects no model sees. The questions below add what pilots in other series say about cloud, wind and storms.",
        "sub": "Understanding weather patterns and atmospheric conditions is crucial for safe paragliding. This section exists to help you build exactly that.",
        "seo_title": "Paragliding Weather Explained: Meteorology | Paragliding Atlas",
        "seo_desc": "How to read a paragliding forecast, and what pilots say about clouds, gust fronts, afternoon wind and local effects: the meteorology section of the knowledge base.",
        "hero_alt": "An abstract drawing: isobars circling a low pressure centre, with an orange cold front trailing from it, its triangles pointing the way it moves",
        "series_heading": "The series",
        "series_kicker": "Built from the episodes",
        "faq_heading": "Questions across the knowledge base",
        "faq": [
            {"q": "Can a cloud suck you in when paragliding?",
             "a": "Not in the way the phrase suggests, says Will Gadd: nobody is sucked into a cloud, they fly in, and once you own that, you can fix it by leaving earlier and checking the radar on your phone. In the Himalaya, Eddie Colfox's advice is to be very careful of cloud, and never to follow someone into one just because they are there.",
             "src": [(WILL, "c13", "Will Gadd"), (EDDIE, "c3", "Eddie Colfox")]},
            {"q": "How can you tell a day will overdevelop?",
             "a": "Watch the clock and the sounding. Eddie Colfox notes what time the clouds form, because early clouds usually mean they will grow big later. On a sounding, Ivelin Kalushkov looks at the dew point: if it runs close to the temperature line over a great height, clouds can grow high enough for storms or rain, while a very dry layer stops them overdeveloping.",
             "src": [(EDDIE, "c4", "Eddie Colfox"), (IK, "c9", "Ivelin Kalushkov"), (IK, "c10", "Ivelin Kalushkov")]},
            {"q": "How do gust fronts catch pilots out?",
             "a": "Often at launch. Eddie Colfox saw one coming across the water just as he turned to launch on the coast, after an older pilot had told him it was too windy; he was lifted, took a big collapse and stalled onto the slope. Ivelin Kalushkov treats any rain radar colour above green, on a day with thunderstorms forecast, as a sign of rain and possible gust fronts.",
             "src": [(EC, "c5", "Eddie Colfox"), (IK, "c7", "Ivelin Kalushkov")]},
            {"q": "When is the wind strongest at a flying site?",
             "a": "Often late in the day. In Ivelin Kalushkov's forecast for Manilla in Australia, the wind was expected to build to gusts of 30 km/h late in the afternoon, so his advice was to be in the air before 3 pm. At Roldanillo in Colombia, the afternoon wind makes landing near town gusty, so Pal Takats lands out near the main road instead.",
             "src": [(IK, "c8", "Ivelin Kalushkov"), (COL, "c12", "Pal Takats")]},
            {"q": "Why can local pilots read the weather better than a forecast?",
             "a": "Because some effects never reach the models. At Manilla, when the wind blows off Lake Keepit, the lake spills cool air into the valley in front of launch from about one o'clock and breaks up the thermals, which no model shows. At Sopot in Bulgaria, strong daytime anabatic winds can overcome a forecast northerly. Ivelin Kalushkov's advice: use local knowledge, and research a site first.",
             "src": [(IK, "c11", "Ivelin Kalushkov"), (IK, "c12", "Ivelin Kalushkov")]},
        ],
    },
    "industry": {
        "kicker": "Industry & Community",
        "h1": "What Happens Behind the Scenes of Paragliding?",
        "lead": "Three series about the people and systems around the flying: how gear is designed and made and what the racing world asks of the brands, pilots' own stories of their closest calls, and the hard questions about competition safety and who is responsible.",
        "sub": "Explore the business side of paragliding and learn from the collective wisdom of our global community.",
        "seo_title": "Behind the Scenes of Paragliding: Industry | Paragliding Atlas",
        "seo_desc": "How paragliding gear is designed and made, pilots' stories of their closest calls, and the hard questions about competition safety: Industry & Community.",
        "hero_alt": "An abstract drawing: a paraglider seen from the front as a pattern of cells, its lines converging on a harness below",
        "series_heading": "The three series",
        "series_kicker": "Built from the episodes",
        "faq_heading": "Questions across these series",
        "faq": [
            {"q": "What should you look at before entering a paragliding competition?",
             "a": "The venue first, says Pal Takats: he now enters a competition because he wants to fly that place, since the site sets much of the risk. Marko Milutinovic weighs the size of the field, and sees more room to fly your own lines at events of around 70 pilots than in 140-pilot championships. Stan Radzikowski adds that pilots are entitled to know where the money goes.",
             "src": [(PAL, "c9", "Pal Takats"), (MM, "c8", "Marko Milutinovic"), (GAGGLE, "c9", "Stan Radzikowski")]},
            {"q": "How high are most reserves thrown?",
             "a": "Lower than most pilots imagine, in Eric Roussel's experience: often 100 to 150 metres above the ground and sometimes 50, too low to recover the wing, which is why Neo designed its reserve system around low throws. Marko Milutinovic, hit more than 1,000 metres up with a shredded wing, had time to wait while it turned slowly, and threw at 400 to 600 metres.",
             "src": [(NEO, "c12", "Eric Roussel"), (MM, "c4", "Marko Milutinovic"), (MM, "c5", "Marko Milutinovic")]},
            {"q": "What does it take to start a paragliding brand?",
             "a": "A love of flying. Eric Roussel's rule for anyone who wants to make gear is to fly and love flying, or it is not a business. Gin Seok Song let results do the talking: pilots on his first competition wings were asked not to say who designed them. Later his company paid a Korean mill to develop a fabric, tested it for years and had it to itself for two.",
             "src": [(NEO, "c4", "Eric Roussel"), (GIN, "c4", "Gin Seok Song"), (GIN, "c12", "Gin Seok Song")]},
            {"q": "Why share stories of accidents and close calls?",
             "a": "Because that is how other pilots learn. Julien Garcia's central demand is that a competition organiser always says what happened, whatever the liability. Bill Hughes adds the other half: check the facts before repeating a story. And Eddie Colfox tells his own accident plainly, to show how one bad decision is usually followed by two or three more before someone gets hurt.",
             "src": [(JULIEN, "c1", "Julien Garcia"), (GOV, "c2", "Bill Hughes"), (EC, "c5", "Eddie Colfox")]},
            {"q": "What makes a paragliding competition safer?",
             "a": "The pilots, in the view of Goran Dimiskovski of the PWCA: pilot quality is the safety system, which is why World Cup places are given on results alone. Stan Radzikowski expects a championship's official landing fields to be proven at earlier events, not checked on the morning of the task. And Bill Belcourt saw pilots who made their own decisions come through a hard event better than a managed field.",
             "src": [(PWCA, "c10", "Goran Dimiskovski"), (GAGGLE, "c3", "Stan Radzikowski"), (BELC, "c11", "Bill Belcourt")]},
        ],
    },
    "technical": {
        "kicker": "Technical Focus & Flight Safety",
        "h1": "What Should Every Pilot Understand About Wings and Gear?",
        "lead": "Three series on the equipment: how a paraglider actually flies and why it collapses, what new technology does and does not change, and what reserves, harnesses, helmets and lines can and cannot do, from the people who design, test and repack them.",
        "sub": "A deep dive into the technical aspects of free flight. Comprehensive knowledge about the mechanics, equipment, and technological advances in paragliding.",
        "seo_title": "Wings and Gear Explained: Technical Focus | Paragliding Atlas",
        "seo_desc": "How a paraglider flies and collapses, what new technology really changes, and what reserves, harnesses and helmets can and cannot do: Technical Focus.",
        "hero_alt": "An abstract drawing: an aerofoil section with streamlines flowing around it and orange arrows showing the lift along its upper surface",
        "series_heading": "The three series",
        "series_kicker": "Built from the episodes",
        "faq_heading": "Questions across these series",
        "faq": [
            {"q": "Will a more advanced wing make you a better pilot?",
             "a": "Not on its own. Frantisek Pavlousek's view is that safety and performance both follow the weakest point of the chain, so a C wing flown by a B pilot gives neither. Stephan Stiegler sets a threshold from the middle of the B class: be ready to stop the pitch, then learn to feel it coming, and you fly the wing rather than the other way round.",
             "src": [(UPF, "c6", "Frantisek Pavlousek"), (STIEG, "c6", "Stephan Stiegler")]},
            {"q": "What should you do when your paraglider collapses?",
             "a": "It depends on the collapse. For a side that drops, SIV coach Helmut Schrempf says to release the tension from your hip on that side; pressing in gives the wing the wrong input and starts it rolling. After a collapse at full speed, Beni Kälin points out that the wing has little pressure inside and reopens slowly hands-up, so countersteer and pump the closed side.",
             "src": [(HELMUT, "c4", "Helmut Schrempf"), (BENI, "c9", "Beni Kälin")]},
            {"q": "Should you practise throwing your reserve?",
             "a": "Yes. In Urs Haari's clinics pilots hang in a simulator the night before and throw, and three in ten cannot get the reserve out of their harness. He calls that the cheapest and most decisive equipment test in the sport, and the one almost nobody does. Then, if you can, throw it for real over water, which Will Gadd recommends too.",
             "src": [(URS, "c7", "Urs Haari"), (WILL, "c13", "Will Gadd")]},
            {"q": "When is the best time to buy a new paraglider model?",
             "a": "Frantisek Pavlousek's long-time flying friends wait until a wing has been on the market for about a year, so that people know how it behaves. When you do choose, Stephan Stiegler suggests reading the designer's description of who the wing is for rather than tallying certification grades, because a low B can fly much like an A in the air.",
             "src": [(UPF, "c10", "Frantisek Pavlousek"), (STIEG, "c7", "Stephan Stiegler")]},
            {"q": "How can you tell whether a wing resists collapses?",
             "a": "Not from the test report alone, says Tom Lolies: reports show how collapses went, never how easily they happen, and a pitch-unstable wing can even score well because it folds so readily. One sign he looks for is slack B lines at full speed, which means the lift has moved forward onto the A lines. It is a green flag among several, not a rule.",
             "src": [(TOM, "c7", "Tom Lolies"), (TOM, "c6", "Tom Lolies")]},
        ],
    },
}
