/* Generated by tools/v4_min.py from src/v4-menu.js: edit the source, then run it. */
(function () {
"use strict";
var d = document, w = window;
var m = /^(.*\/prototypes\/v\d+\/)/.exec(location.pathname);
var BASE = m ? m[1] : "/";                        // the prototype's root
var LIVE = m ? BASE.replace(/prototypes\/v\d+\/$/, "") : "/"; // the site's root (the assets)
var IDX = m ? BASE + "search-index.js" : "/assets/v4/search-index.js";
var KB = m ? BASE + "img/kb/" : "/assets/v4/img/kb/";   // the kit's drawings (@kb/ in a picture's path)
var SECTIONS = [
["Expeditions", "index.html#destinations", "assets/destinations/india/hero/snowline.webp", [["India", "destinations/india.html"], ["Kenya", "destinations/kenya.html"]]],
["Podcast", "podcast.html", "assets/images/pod-hero-gemona.webp", [["Library", "library.html"], ["Topics", "tags.html"]]],
["Knowledge Base", "knowledge-base.html", "@kb/kb-flight-mechanics.svg", []],
["About", "about.html", "assets/images/partners-aninder.webp", [["Mission Statement", "mission.html"], ["Partner With Me", "partners.html"]]]
];
var menu = null, lastFocus = null, idx = null;
function esc(s) { return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;"); }
function build() {
menu = d.createElement("div");
menu.className = "v4-menu";
menu.id = "v4Menu";
menu.setAttribute("role", "dialog");
menu.setAttribute("aria-modal", "true");
menu.setAttribute("aria-label", "Menu and search");
menu.hidden = true;
var here = location.pathname.slice(BASE.length);
var go = SECTIONS.map(function (s, i) {
var cur = d.querySelector('.v4-nav a.is-here');
var on = cur && cur.textContent.trim() === s[0];
return '<li class="v4-mg' + (on ? " is-here" : "") + '"><a class="v4-mg-a" href="' + BASE + s[1] + '"' + (on ? ' aria-current="page"' : "") + '>' +
'<span class="v4-mg-img' + (s[2].indexOf("@kb/") === 0 ? " is-drawing" : "") + '" data-bg="' + (s[2].indexOf("@kb/") === 0 ? KB + s[2].slice(4) : LIVE + s[2]) + '" aria-hidden="true"></span>' +
'<span class="v4-mg-n" aria-hidden="true">0' + (i + 1) + '</span><span class="v4-mg-t">' + s[0] + '</span></a>' +
(s[3].length ? '<span class="v4-mg-sub">' + s[3].map(function (x) { return '<a href="' + BASE + x[1] + '">' + x[0] + '</a>'; }).join("") + '</span>' : "") +
'</li>';
}).join("");
function homeMark() {
var lg = d.querySelector(".page-wrap > nav .wordmark img");
return lg ? '<img src="' + lg.getAttribute("src") + '" alt="Paragliding Atlas" width="480" height="100">' : "Paragliding Atlas";
}
menu.innerHTML =
'<div class="v4-menu-in">' +
'<div class="v4-menu-bar"><a class="v4-menu-home" href="' + BASE + 'index.html">' + homeMark() + '</a>' +
'<button type="button" class="v4-menu-x" aria-label="Close menu"><span aria-hidden="true"></span></button></div>' +
'<div class="v4-menu-search" role="search"><label class="v4-menu-lab" for="v4q">Search episodes, the knowledge base and trips</label>' +
'<input id="v4q" type="search" autocomplete="off" placeholder="Search" aria-controls="v4hits">' +
'<ol class="v4-hits" id="v4hits" aria-live="polite"></ol></div>' +
'<ul class="v4-menu-go">' + go + '</ul>' +
'<div class="v4-menu-foot"><a class="btn-solid" href="' + BASE + 'enquire.html"><span>Enquire Now</span></a>' +
'<a class="btn-lines" href="' + BASE + 'sitemap.html">Sitemap</a></div>' +
'</div>';
d.body.appendChild(menu);
menu.querySelector(".v4-menu-x").addEventListener("click", close);
menu.addEventListener("click", function (e) {
var l = e.target.closest && e.target.closest("a[href]");
if (l && l.hash && l.pathname === location.pathname) close();
});
menu.addEventListener("keydown", function (e) {
if (e.key === "Escape") { e.preventDefault(); close(); return; }
if (e.key !== "Tab") return;
var f = [].slice.call(menu.querySelectorAll("a[href], button, input")).filter(function (x) { return x.offsetParent !== null; });
if (!f.length) return;
if (e.shiftKey && d.activeElement === f[0]) { e.preventDefault(); f[f.length - 1].focus(); }
else if (!e.shiftKey && d.activeElement === f[f.length - 1]) { e.preventDefault(); f[0].focus(); }
});
var q = menu.querySelector("#v4q");
q.addEventListener("input", function () { search(q.value); });
q.addEventListener("focus", loadIndex, { once: true });
}
var loadingIdx = false, last = null;          // last: the search waiting for the index ([words, list])
function loadIndex() {
if (idx || w.V4_SEARCH) { idx = w.V4_SEARCH; return; }
if (loadingIdx) return;
loadingIdx = true;
var s = d.createElement("script");
s.src = IDX;
s.onload = function () { idx = w.V4_SEARCH || []; if (last) render(last[0], last[1]); };
s.onerror = function () {
loadingIdx = false;
if (last) last[1].innerHTML = '<li class="v4-hit-none">The search could not load. The <a href="' + IDX.replace(/[^\/]*$/, "") + 'sitemap.html">sitemap</a> lists every page.</li>';
};
d.head.appendChild(s);
}
function search(v) { render(v, menu.querySelector("#v4hits")); }
function render(v, ol) {
v = v.trim().toLowerCase();
last = [v, ol];
if (!v) { ol.innerHTML = ""; return; }
if (!idx) { loadIndex(); return; }
var STOP = " a an and are can do does for how i in is it me much my of on or the to what when where which who why will with you your ";
var NEAR = { cost: ["price", "fee"], costs: ["price", "fee"], price: ["cost", "fee"], prices: ["cost", "fee"], fee: ["price", "cost"],
date: ["departure", "when"], dates: ["departure", "when"], departure: ["date"], book: ["booking", "hold a place"], booking: ["book", "hold a place"] };
var TRIPWORDS = /\b(kenya|india|bir|billing|trip|trips|tour|tours|expedition|expeditions|cost|costs|price|prices|fee|date|dates|departure|departures|book|booking|deposit|cancellation|refund|visa|insurance|hold)\b/;
var words = v.split(/\s+/).filter(function (x) { return x && STOP.indexOf(" " + x + " ") === -1; });
if (!words.length) words = v.split(/\s+/).filter(Boolean);
var need = words.length <= 2 ? words.length : Math.ceil(words.length * 0.6);
var tripQ = TRIPWORDS.test(v);
function forms(x) { var f = x.length > 3 && /s$/.test(x) ? [x, x.slice(0, -1)] : [x]; return f.concat(NEAR[x] || []); }
var hits = [];
for (var i = 0; i < idx.length; i++) {
var e = idx[i], t = e.t.toLowerCase(), dsc = e.d.toLowerCase(), h = (e.h || "").toLowerCase();
var found = 0, score = 0;
words.forEach(function (x) {
var f = forms(x), w = 0;
f.forEach(function (y) { w = Math.max(w, t.indexOf(y) !== -1 ? 3 : dsc.indexOf(y) !== -1 ? 2 : h.indexOf(y) !== -1 ? 1 : 0); });
if (w) { found++; score += w; }
});
if (found >= need) hits.push([score + found * 2 + (tripQ && e.k === "Trip" ? 100 : 0), e]);
}
hits.sort(function (a, b) { return b[0] - a[0]; });
function line(e) {
var best = "", n = 0;
(e.h || "").split(" \u00b7 ").forEach(function (x) {
var lx = x.toLowerCase(), c = 0;
words.forEach(function (w) { if (forms(w).some(function (y) { return lx.indexOf(y) !== -1; })) c++; });
if (c > n) { n = c; best = x; }
});
var dl = e.d.toLowerCase(), dn = 0;
words.forEach(function (w) { if (forms(w).some(function (y) { return dl.indexOf(y) !== -1; })) dn++; });
var out = dn >= n && e.d ? e.d : best || e.d;
return out.length > 140 ? out.slice(0, 137).replace(/\s+\S*$/, "") + "\u2026" : out;
}
ol.innerHTML = hits.length ? hits.slice(0, 8).map(function (h) {
var e = h[1], l = line(e);
return '<li><a href="' + BASE + e.u + '"><span class="v4-hit-k">' + esc(e.k) + '</span><span class="v4-hit-t">' + esc(e.t) +
(l ? '<span class="v4-hit-s">' + esc(l) + "</span>" : "") + "</span></a></li>";
}).join("") : '<li class="v4-hit-none">Nothing found. <a href="' + BASE + 'tags.html">Topics</a> <a href="' + BASE +
'library.html">Library</a> <a href="' + BASE + 'destinations/india.html">India</a> <a href="' + BASE + 'destinations/kenya.html">Kenya</a></li>';
}
function open(focusSearch) {
if (!menu) build();
menu.querySelectorAll("[data-bg]").forEach(function (x) { x.style.backgroundImage = "url('" + x.getAttribute("data-bg") + "')"; x.removeAttribute("data-bg"); });
lastFocus = d.activeElement;
menu.hidden = false;
d.documentElement.classList.add("v4-menu-open");
requestAnimationFrame(function () { menu.classList.add("is-open"); });
(focusSearch ? menu.querySelector("#v4q") : menu.querySelector(".v4-menu-x")).focus();
syncButtons(true);
}
function close() {
if (!menu || menu.hidden) return;
menu.classList.remove("is-open");
d.documentElement.classList.remove("v4-menu-open");
menu.hidden = true;
syncButtons(false);
if (lastFocus && lastFocus.focus) lastFocus.focus();
}
function syncButtons(o) {
d.querySelectorAll(".v4-open, .nav-toggle").forEach(function (b) { b.setAttribute("aria-expanded", o ? "true" : "false"); b.setAttribute("aria-controls", "v4Menu"); });
}
window.V4_MENU = { open: open, close: close, find: function (v, ol) { loadIndex(); render(v, ol); } };
return;
function mount() {
var nav = d.querySelector(".page-wrap > nav");
if (!nav) return;
var cta = nav.querySelector(".nav-cta");
var b = d.createElement("button");
b.type = "button";
b.className = "v4-open";
b.setAttribute("aria-controls", "v4Menu");
b.setAttribute("aria-expanded", "false");
b.innerHTML = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" aria-hidden="true"><circle cx="11" cy="11" r="6.5"/><path d="M20 20l-4.2-4.2"/></svg><span>Search</span>';
b.addEventListener("click", function () { open(true); });
if (cta) nav.insertBefore(b, cta); else nav.appendChild(b);
d.addEventListener("click", function (e) {
var t = e.target.closest && e.target.closest(".nav-toggle");
if (!t) return;
e.preventDefault(); e.stopImmediatePropagation();
open(false);
}, true);
}
})();
