#!/usr/bin/env python3
"""Write `globe-episodes.js`: what the globe popup shows when a pin is clicked.

The popup used to show a hardcoded line, the title and a link. Everything here
was already in the site's own data or computable from it, and none of it was
being used.

RANGE AND BEARING ARE REAL.
Great circle distance and initial bearing from Oslo, calculated from each pin's
own longitude and latitude with the haversine and forward azimuth formulas. Cuba
really is 7,987 km out on 282 degrees. This matters: a readout that looks like an
instrument but prints invented numbers is a costume, and anybody who checks one
against a map would find out.

Oslo is not arbitrary either. It is the coordinate already printed in the site's
own navigation bar, so the two agree.
"""
import json
import math
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OSLO = (59.9139, 10.7522)          # the coordinate in the site nav
EARTH_KM = 6371.0
POINTS = ["N", "NNE", "NE", "ENE", "E", "ESE", "SE", "SSE",
          "S", "SSW", "SW", "WSW", "W", "WNW", "NW", "NNW"]


def great_circle_km(a, b):
    la1, lo1, la2, lo2 = map(math.radians, [a[0], a[1], b[0], b[1]])
    h = (math.sin((la2 - la1) / 2) ** 2
         + math.cos(la1) * math.cos(la2) * math.sin((lo2 - lo1) / 2) ** 2)
    return EARTH_KM * 2 * math.asin(math.sqrt(h))


def initial_bearing(a, b):
    la1, lo1, la2, lo2 = map(math.radians, [a[0], a[1], b[0], b[1]])
    y = math.sin(lo2 - lo1) * math.cos(la2)
    x = math.cos(la1) * math.sin(la2) - math.sin(la1) * math.cos(la2) * math.cos(lo2 - lo1)
    return (math.degrees(math.atan2(y, x)) + 360) % 360


def pins():
    """slug -> (lon, lat), read from globe.js, the only place they exist."""
    src = open(os.path.join(ROOT, "globe.js"), encoding="utf-8").read()
    out = {}
    for _q, _t, href, lon, lat in re.findall(
            r"\[\s*([\"'])(.*?)\1\s*,\s*'(episodes/[^']+)'\s*,\s*(-?[\d.]+)\s*,\s*(-?[\d.]+)\s*\]",
            src, re.S):
        out[href.split("/")[-1].replace(".html", "")] = (float(lon), float(lat))
    return out


def main():
    meta = {e["slug"]: e for e in
            json.load(open(os.path.join(ROOT, "episode-meta.json"), encoding="utf-8"))}
    out = {}
    for slug, (lon, lat) in pins().items():
        e = meta.get(slug)
        if not e:
            continue
        km = great_circle_km(OSLO, (lat, lon))
        brg = initial_bearing(OSLO, (lat, lon))
        out[slug] = {
            "title": e.get("title", ""),
            "guest": (e.get("guest") or "").strip(),
            "series": (e.get("series") or "").strip(),
            "epno": (e.get("epno") or "").strip(),
            "dur": (e.get("duration_label") or "").strip(),
            "nch": len(e.get("chapters") or []),
            "video": (e.get("video_id") or "").strip(),
            "lat": lat, "lon": lon,
            "km": int(round(km)),
            "brg": int(round(brg)) % 360,
            "card": POINTS[int((brg + 11.25) % 360 // 22.5)],
            # Five episodes are pinned at the studio itself. "0 km on a bearing
            # of 196 degrees" is not a fact, it is a rounding artefact, so those
            # say where they are instead of how far away they are.
            "home": km < 5,
        }
    body = ("/* Generated by tools/generate_globe_episodes.py. Do not edit.\n"
            "   Range and bearing are great circle distance and initial bearing from\n"
            "   Oslo (59.9139N 10.7522E), the coordinate in the site navigation. */\n"
            "window.GLOBE_EP = " + json.dumps(out, ensure_ascii=False, sort_keys=True) + ";\n")
    open(os.path.join(ROOT, "globe-episodes.js"), "w", encoding="utf-8").write(body)
    print("wrote globe-episodes.js: %d pins, %d KB" % (len(out), len(body.encode()) // 1024))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
