#!/usr/bin/env python3
"""Write `library-episodes.js`: the popup payload for every library row.

WHY A SEPARATE FILE AND NOT AN INLINE BLOCK
The knowledge base pages carry their popup data inline, because each holds only
six or twelve episodes. The library holds all 86 on one page, and inlining that
would add roughly 150 KB to a page that is already the heaviest on the site. As
a separate script it is cached once and reused on every visit.

KEYED BY SLUG, NOT BY INDEX
The knowledge base tiles are generated once and never move, so an index is fine
there. The library re-renders its grid on every filter and sort, so an index
would point at the wrong episode the moment somebody clicked "Longest first".
"""
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "tools"))
import kb_modal_data as KBD  # noqa: E402

SERIES_PAGE = {
    "Navigators": "navigators", "Sky Gods": "sky-gods",
    "Living the Dream": "living-the-dream", "World Cups": "world-cups",
    "Risk vs Reward": "risk-vs-reward", "Resources, Tools and Tips": "resources-tools-tips",
    "Weather Patterns": "weather-patterns", "Brand Stories": "brand-stories",
    "Storytellers": "storytellers", "The Dark Side": "the-dark-side",
    "Flight Mechanics": "flight-mechanics", "New Technologies": "new-technologies",
    "Know Your Equipment": "know-your-equipment",
}


def library_rows():
    """The episodes listed in library-data.js, in file order."""
    src = open(os.path.join(ROOT, "library-data.js"), encoding="utf-8").read()
    body = re.search(r"LIB_EPISODES\s*=\s*\[(.*?)\n\];", src, re.S)
    rows = []
    for m in re.finditer(r"\{[^{}]*\}", body.group(1)):
        chunk = m.group(0)
        page = re.search(r'page:\s*"([^"]*)"', chunk)
        if page:
            rows.append(page.group(1))
    return rows


def main():
    meta = {e["slug"]: e for e in
            json.load(open(os.path.join(ROOT, "episode-meta.json"), encoding="utf-8"))}
    out, missing = {}, []
    for slug in library_rows():
        e = meta.get(slug)
        if not e:
            missing.append(slug)
            continue
        series = (e.get("series") or "").strip()
        d = KBD.modal_data(e["title"], e.get("guest", ""), series,
                           "knowledge-base/%s.html" % SERIES_PAGE.get(series, ""))
        if d is None:
            missing.append(slug)
            continue
        # The library sits at the site root, one level up from the knowledge
        # base pages these paths were written for.
        d["page"] = "episodes/%s.html" % slug
        d["seriesPage"] = ("knowledge-base/%s.html" % SERIES_PAGE[series]
                           if series in SERIES_PAGE else "")
        d["libRoot"] = True
        # The guest is in the title on almost every episode, and the artwork
        # usually says it too. Same rule as the knowledge base cards.
        shown_title, shown_guest = KBD.display_title(d["title"], d["guest"])
        d["shownTitle"] = shown_title
        d["shownGuest"] = shown_guest or ""
        out[slug] = d

    if missing:
        print("  no popup data for %d row(s): %s" % (len(missing), missing[:4]))
    body = ("/* Generated by tools/generate_library_episodes.py. Do not edit. */\n"
            "window.LIB_MODAL = " + json.dumps(out, ensure_ascii=False, sort_keys=True) + ";\n")
    path = os.path.join(ROOT, "library-episodes.js")
    open(path, "w", encoding="utf-8").write(body)
    print("wrote library-episodes.js: %d episodes, %d KB"
          % (len(out), len(body.encode()) // 1024))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
