#!/usr/bin/env python3
"""
v4's served style sheet and immersion script, from their readable sources.

  prototypes/v4/src/v2.css            ->  prototypes/v4/v2.css
  prototypes/v4/src/v2-immersive.js   ->  prototypes/v4/v2-immersive.js
  prototypes/v4/src/v4-menu.js        ->  prototypes/v4/v4-menu.js (loaded on first use)

Edit the sources (they carry every comment); this writes the served copies
without comments and spare white space, so v4 is not heavier on arrival than
v2 (docs/v4-plan.md step 6). Conservative on purpose: CSS loses comments and
white space; the script loses its comment blocks and comment lines and its
indentation, nothing inside a line of code is touched.

    python3 tools/v4_min.py
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
V4 = os.path.join(ROOT, "prototypes", "v4")
HEAD = "/* Generated by tools/v4_min.py from src/%s: edit the source, then run it. */\n"


def css(src):
    s = re.sub(r"/\*.*?\*/", "", src, flags=re.S)
    s = re.sub(r"\s+", " ", s)
    s = re.sub(r"\s*([{};,>])\s*", r"\1", s)
    s = s.replace(";}", "}")
    return s.strip() + "\n"


def js(src):
    s = re.sub(r"/\*.*?\*/", "", src, flags=re.S)
    out = []
    for ln in s.split("\n"):
        t = ln.strip()
        if not t or t.startswith("//"):
            continue
        out.append(t)
    return "\n".join(out) + "\n"


def main():
    for name, fn in (("v2.css", css), ("v2-immersive.js", js), ("v4-menu.js", js)):
        src = open(os.path.join(V4, "src", name), encoding="utf-8").read()
        out = HEAD % name + fn(src)
        open(os.path.join(V4, name), "w", encoding="utf-8").write(out)
        print("v4 min: %s %d -> %d bytes" % (name, len(src.encode()), len(out.encode())))


if __name__ == "__main__":
    main()
