#!/usr/bin/env python3
"""
The one search (docs/v4-plan.md step 5): an index of the v4 pages' own titles
and descriptions (no new text), across episodes, the knowledge base, the trips,
topics and the rest. Written to prototypes/v4/search-index.js; the menu loads
it only when the search is opened.

    python3 tools/v4_search.py
"""
import html
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
V4 = os.path.join(ROOT, "prototypes", "v4")
SKIP = {"404.html", "styleguide.html", "fly-options.html"}


def kind(rel):
    if rel.startswith("episodes/"):
        return "Episode"
    if rel.startswith("knowledge-base"):
        return "Knowledge base"
    if rel.startswith("destinations/"):
        return "Trip"
    if rel.startswith("tags"):
        return "Topic"
    return "Page"


def main():
    out = []
    for d, _, fs in os.walk(V4):
        for f in fs:
            if not f.endswith(".html"):
                continue
            rel = os.path.relpath(os.path.join(d, f), V4).replace(os.sep, "/")
            if rel in SKIP or rel.startswith("samples/"):
                continue
            src = open(os.path.join(d, f), encoding="utf-8").read()
            if 'http-equiv="refresh"' in src[:4000]:
                continue
            t = re.search(r"<title>(.*?)</title>", src, re.S)
            m = re.search(r'<meta name="description" content="([^"]*)"', src)
            if not t:
                continue
            title = re.sub(r"\s*\|\s*Paragliding Atlas\s*$", "", html.unescape(t.group(1)).strip())
            out.append({"t": title, "d": html.unescape(m.group(1)) if m else "", "u": rel, "k": kind(rel)})
    order = {"Trip": 0, "Page": 1, "Knowledge base": 2, "Topic": 3, "Episode": 4}
    out.sort(key=lambda e: (order[e["k"]], e["t"].lower()))
    js = ("/* Generated by tools/v4_search.py: the v4 pages' own titles and descriptions. */\n"
          "window.V4_SEARCH = " + json.dumps(out, ensure_ascii=False, separators=(",", ":")) + ";\n")
    open(os.path.join(V4, "search-index.js"), "w", encoding="utf-8").write(js)
    print("v4 search: %d pages, %d KB" % (len(out), len(js) // 1024))


if __name__ == "__main__":
    main()
