#!/usr/bin/env python3
"""
The one search (docs/v4-plan.md step 5): an index of the v4 pages' own titles
and descriptions (no new text), across episodes, the knowledge base, the trips,
topics and the rest; with each page's own headings and questions (an
episode's chapter titles, a trip's FAQ), so "price" or "speed bar" find the
page that answers them. Topic pages, the library and the listing pages repeat
episode titles as headings, so theirs are left out. Written to prototypes/v4/search-index.js; the menu loads
it only when the search is opened.

    python3 tools/v4_search.py
"""
import html
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from v4_ux import topic_case   # noqa: E402  (20: SRS and CCC as the site writes them)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
V4 = os.path.join(ROOT, "prototypes", "v4")
SKIP = {"404.html", "styleguide.html", "fly-options.html"}
LISTS = ("tags", "library.html", "podcast.html", "index.html", "sitemap.html", "knowledge-base.html")
GENERIC = {"read more", "more", "about", "chapters", "full transcript", "in short", "the guest", "topics", "up next"}


def headings(rel, src):
    """The page's own h2/h3 headings and <summary> questions, in order, once each."""
    if rel.startswith(LISTS):
        return ""
    a = src.find("<main")
    body = src[a if a >= 0 else 0:]
    body = re.split(r"<footer\b", body)[0]
    found = re.findall(r"<h[23][^>]*>(.*?)</h[23]>", body, re.S) + re.findall(r"<summary[^>]*>(.*?)</summary>", body, re.S)
    out = []
    for x in found:
        t = html.unescape(re.sub(r"\s+", " ", re.sub(r"<[^>]+>", " ", x))).strip()
        if 3 < len(t) < 140 and t.lower() not in GENERIC and t not in out:
            out.append(t)
    return " · ".join(out)


def kind(rel):
    if rel.startswith("episodes/"):
        return "Episode"
    if rel.startswith("knowledge-base"):
        return "Knowledge base"
    if rel.startswith("destinations/"):
        return "Trip"
    if rel.startswith("tags"):
        return "Topic"
    return "Page"


def norm(t):
    """As v2-library.js normalises: lower case, letters and digits, single spaces."""
    return re.sub(r"\s+", " ", re.sub(r"[^a-z0-9 ]+", " ", html.unescape(t).lower())).strip()


def library_find():
    """The usability pass (17): what the library's search can also match, besides a card's title and guest:
    each episode's topics, chapter titles and summary (episode-meta.json, read only), and the topics with a
    page, for the empty state, and the code that shows them (src/v4-ux-libfind.js). Written to
    prototypes/v4/library-find.js; the library loads it on the first keystroke, so no one pays for it on arrival."""
    meta = json.load(open(os.path.join(ROOT, "episode-meta.json"), encoding="utf-8"))
    eps, count = {}, {}
    for m in meta:
        tags = [t for t in (m.get("tags") or []) if t]
        words = " ".join(tags + [c.get("title", "") for c in (m.get("chapters") or [])] + [m.get("summary") or ""])
        eps["episodes/%s.html" % m["slug"]] = norm(words)
        for t in tags:
            count[t] = count.get(t, 0) + 1
    topics = []
    for t, n in sorted(count.items(), key=lambda kv: (-kv[1], kv[0])):
        slug = re.sub(r"[^a-z0-9]+", "-", t.lower()).strip("-")
        if os.path.exists(os.path.join(V4, "tags", slug + ".html")):
            topics.append([t, "tags/%s.html" % slug, n])
    js = ("/* Generated by tools/v4_search.py: what the library's search matches besides titles and guests"
          " (topics, chapter titles, summaries), and the topics for its empty state. */\n"
          "window.V4_LIBFIND = " + topic_case(json.dumps({"eps": eps, "topics": topics}, ensure_ascii=False, separators=(",", ":"))) + ";\n")
    import v4_min                       # and the code and styles that show them (src/v4-ux-libfind.js, src/v4-ux.css), off the library's first load
    ux = open(os.path.join(V4, "src", "v4-ux.css"), encoding="utf-8").read()
    css = re.search(r"/\* @page libfind \*/(.*?)(?=/\* @page |\Z)", ux, re.S)
    js += "window.V4_LIBFIND_CSS = %s;\n" % json.dumps(v4_min.css(css.group(1)).strip() if css else "")
    js += v4_min.js(open(os.path.join(V4, "src", "v4-ux-libfind.js"), encoding="utf-8").read())
    open(os.path.join(V4, "library-find.js"), "w", encoding="utf-8").write(js)
    print("v4 library find: %d episodes, %d topics, %d KB" % (len(eps), len(topics), len(js) // 1024))


def main():
    library_find()
    out = []
    for d, _, fs in os.walk(V4):
        for f in fs:
            if not f.endswith(".html"):
                continue
            rel = os.path.relpath(os.path.join(d, f), V4).replace(os.sep, "/")
            if rel in SKIP or rel.startswith("samples/"):
                continue
            src = open(os.path.join(d, f), encoding="utf-8").read()
            if 'http-equiv="refresh"' in src[:4000]:
                continue
            t = re.search(r"<title>(.*?)</title>", src, re.S)
            m = re.search(r'<meta name="description" content="([^"]*)"', src)
            if not t:
                continue
            title = re.sub(r"\s*\|\s*Paragliding Atlas(?: episodes)?\s*$", "", html.unescape(t.group(1)).strip())   # "Reserves | Paragliding Atlas episodes"
            e = {"t": title, "d": html.unescape(m.group(1)) if m else "", "u": rel, "k": kind(rel)}
            h = headings(rel, src)
            if h:
                e["h"] = h
            out.append(e)
    order = {"Trip": 0, "Page": 1, "Knowledge base": 2, "Topic": 3, "Episode": 4}
    out.sort(key=lambda e: (order[e["k"]], e["t"].lower()))
    js = ("/* Generated by tools/v4_search.py: the v4 pages' own titles and descriptions. */\n"
          "window.V4_SEARCH = " + topic_case(json.dumps(out, ensure_ascii=False, separators=(",", ":"))) + ";\n")
    open(os.path.join(V4, "search-index.js"), "w", encoding="utf-8").write(js)
    print("v4 search: %d pages, %d KB" % (len(out), len(js) // 1024))


if __name__ == "__main__":
    main()
